### ISSUE TITLE
Updating order status - Invalid rest param status

### ISSUE THREAD

**Issue by vasikgreif** [woocommerce/wc-api-php#100]
I'm trying to update order status. As soon as I add status parameter to the call, I get 

```
Fatal error: Uncaught exception 'Automattic\WooCommerce\HttpClient\HttpClientException' with message 'Error: Invalid parameter(s): status [rest_invalid_param]'
```

The same is when I try to create the order with the `status` parameter. Am I missing something?

**Comment by claudiosanches** [comment]
Looks like you ignored the examples and it's not catching exceptions.
And the error is that you are using invalid parameters.
But no bug on REST API library, just need to properly use it.

**Comment by vasikgreif** [comment]
My problem is not the Fatal Error, but the `invalid parameter` problem. Regarding the WooCommerce [docs](https://woocommerce.github.io/woocommerce-rest-api-docs/#update-an-order), `status` should be a valid parameter. When I pass other params, such as billing info, the order updates just fine.

```
        $api->update_order(7666,[
            // This results in the error for some reason
            // 'status' => 'wc-processing',
            'billing' => [
                'first_name' => 'Jan',
                'last_name' => 'Vomacka - Test',

            ],
        ]);
```

**Comment by claudiosanches** [comment]
@vasikgreif it's a valid parameter, still you are using it wrong:

![screenshot from 2017-04-02 16-23-24](https://cloud.githubusercontent.com/assets/1264099/24590278/bebc9cae-17c0-11e7-8e9c-45ea902c2eb2.png)

And still is not an issue on this REST API library.

Note that the link you pasted here uses an example without `wc-`:

```php
$data = [
    'status' => 'completed'
];
```

**Comment by vasikgreif** [comment]
Ups, you're right. Thanks, and sorry for such a noob mistake.

**Comment by claudiosanches** [comment]
@vasikgreif no worry, but not that this repository is only for issues with the PHP library.
