### ISSUE TITLE
API product -> Categories not returning Category ID

### ISSUE THREAD

**Issue by Sturzaker123** [woocommerce/wc-api-php#101]
**## EXPLANATION OF THE ISSUE**
Call print_r($woocommerce->get('products')

Expected:

```
"categories": [
      {
        "id": 9,
        "name": "Clothing",
        "slug": "clothing"
      },
```

Received:
only returning the name...

```
 ["categories"]=>
    array(1) {
      [0]=>
      string(9) "Chainsaws"
    }


```which is no good because there can be 5 categories with the same name.

How do I get it to return the ID like it shows in the documentation.


**## STEPS TO REPRODUCE THE ISSUE**

When I call

http://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-products

<?php print_r($woocommerce->get('products')); ?>

I Get returned:

```
array(2) {
  ["product"]=>
  array(58) {
    ["title"]=>
    string(14) "Tooline Prod 1"
    ["id"]=>
    int(103)
    ["created_at"]=>
    string(20) "2017-04-01T01:50:28Z"
    ["updated_at"]=>
    string(20) "2017-04-01T01:51:20Z"
    ["type"]=>
    string(6) "simple"
    ["status"]=>
    string(5) "trash"
    ["downloadable"]=>
    bool(false)
    ["virtual"]=>
    bool(false)
    ["permalink"]=>
    string(65) "http://localhost:84/wordpress/product/tooline-prod-1__trashed-32/"
    ["sku"]=>
    string(14) "TOOLINE PROD 1"
    ["price"]=>
    string(4) "0.00"
    ["regular_price"]=>
    string(4) "0.00"
    ["sale_price"]=>
    NULL
    ["price_html"]=>
    string(0) ""
    ["taxable"]=>
    bool(true)
    ["tax_status"]=>
    string(7) "taxable"
    ["tax_class"]=>
    string(0) ""
    ["managing_stock"]=>
    bool(false)
    ["stock_quantity"]=>
    int(0)
    ["in_stock"]=>
    bool(true)
    ["backorders_allowed"]=>
    bool(false)
    ["backordered"]=>
    bool(false)
    ["sold_individually"]=>
    bool(false)
    ["purchaseable"]=>
    bool(false)
    ["featured"]=>
    bool(false)
    ["visible"]=>
    bool(true)
    ["catalog_visibility"]=>
    string(7) "visible"
    ["on_sale"]=>
    bool(false)
    ["product_url"]=>
    string(0) ""
    ["button_text"]=>
    string(0) ""
    ["weight"]=>
    NULL
    ["dimensions"]=>
    array(4) {
      ["length"]=>
      string(1) "0"
      ["width"]=>
      string(1) "0"
      ["height"]=>
      string(1) "0"
      ["unit"]=>
      string(2) "cm"
    }
    ["shipping_required"]=>
    bool(true)
    ["shipping_taxable"]=>
    bool(true)
    ["shipping_class"]=>
    string(0) ""
    ["shipping_class_id"]=>
    NULL
    ["description"]=>
    string(22) "
TEST TL PRod 1

"
    ["short_description"]=>
    string(20) "
uyyiryiryiyu

"
    ["reviews_allowed"]=>
    bool(true)
    ["average_rating"]=>
    string(4) "0.00"
    ["rating_count"]=>
    int(0)
    ["related_ids"]=>
    array(1) {
      [0]=>
      int(104)
    }
    ["upsell_ids"]=>
    array(0) {
    }
    ["cross_sell_ids"]=>
    array(0) {
    }
    ["parent_id"]=>
    int(0)
    ["categories"]=>
    array(1) {
      [0]=>
      string(9) "Chainsaws"
    }
    ["tags"]=>
    array(0) {
    }
    ["images"]=>
    array(2) {
      [0]=>
      array(7) {
        ["id"]=>
        int(102)
        ["created_at"]=>
        string(20) "2017-04-01T01:45:16Z"
        ["updated_at"]=>
        string(20) "2017-04-01T01:45:16Z"
        ["src"]=>
        string(70) "http://localhost:84/wordpress/wp-content/uploads/2017/04/image-17.jpeg"
        ["title"]=>
        string(0) ""
        ["alt"]=>
        string(0) ""
        ["position"]=>
        int(0)
      }
      [1]=>
      array(7) {
        ["id"]=>
        int(101)
        ["created_at"]=>
        string(20) "2017-04-01T01:45:15Z"
        ["updated_at"]=>
        string(20) "2017-04-01T01:45:15Z"
        ["src"]=>
        string(70) "http://localhost:84/wordpress/wp-content/uploads/2017/04/image-16.jpeg"
        ["title"]=>
        string(0) ""
        ["alt"]=>
        string(0) ""
        ["position"]=>
        int(1)
      }
    }
    ["featured_src"]=>
    string(70) "http://localhost:84/wordpress/wp-content/uploads/2017/04/image-17.jpeg"
    ["attributes"]=>
    array(0) {
    }
    ["downloads"]=>
    array(0) {
    }
    ["download_limit"]=>
    int(0)
    ["download_expiry"]=>
    int(0)
    ["download_type"]=>
    string(0) ""
    ["purchase_note"]=>
    string(0) ""
    ["total_sales"]=>
    int(0)
    ["variations"]=>
    array(0) {
    }
    ["parent"]=>
    array(0) {
    }
  }
```
According to documentation it should be displayed in this format: http://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-products

```
"categories": [
      {
        "id": 9,
        "name": "Clothing",
        "slug": "clothing"
      },
```
but it is only returning the name...

```
 ["categories"]=>
    array(1) {
      [0]=>
      string(9) "Chainsaws"
    }

```which is no good because there can be 5 categories with the same name.

How do I get it to return the ID like it shows in the documentation.

```
When I use postman it works fine?

![image](https://cloud.githubusercontent.com/assets/26920527/24701084/4dbaa0fc-1a4d-11e7-8878-b6170bbae05b.png)

`

**Comment by claudiosanches** [comment]
Not an issue with this REST API library, tested and works just fine.
Maybe some problem with your PHP installation or in your WooCommerce.

**Comment by chrisjoshuamartin** [comment]
I having the same problem as Sturzaker123, just the names returned. I'm on the latest version of Woocommerce. I'll keep digging.

**Comment by Sturzaker123** [comment]
Hi Chris, it is an error with his code when the call is received (I couldn't figure it out), I ended up using a different script and all worked 100%,, wasn't a local sever issue either as I tried on different peoples severs also.

**Comment by chrisjoshuamartin** [comment]
Thanks Sturzaker123, good to know!

**Comment by chrisjoshuamartin** [comment]
To go full circle, I ended up figuring out what the issue was... It turns out it was the api version:

With the following settings, the product endpoint will return categories with slug, id, and name.
			[
				'wp_api' => true,
				'version' => 'wc/v1'
			]

One thing that took me a long time to figure out is how to increase the page limit when having 'wp_api' set to true. Anyways it's as easy as passing in posts_per_page as a filter. Hope that helps someone else.... or maybe it was obvious. Heh.

**Comment by AmitPatel-BoTreeConsulting** [comment]
I am facing the same issue. All it returns is just names like `categories":["Life","Clothing","SPORT","ACCESSORIES","Hats+Caps"]`

I tried using cURL as well as Ruby. Also tried with v1 and v3 API urls. 

Even if it would have returned categories with id and slug, adding parent would help a lot as we have many categories having same name like `Clothing` but different parents.

**Comment by Sturzaker123** [comment]
Did you try V2?
