### ISSUE TITLE
woocommerce_rest_authentication_error with in_stock = false

### ISSUE THREAD

**Issue by poyzn** [woocommerce/wc-api-php#102]
Hello.
Got the next error while trying to obtain a list of products via API with

`$more_products = $woocommerce->get('products' , [ "in_stock" => false, 'per_page' => 30, 'page' => 1, 'orderby' => 'title', 'order' => 'asc' ]);`

> Fatal error: Uncaught exception 'Automattic\WooCommerce\HttpClient\HttpClientException' 
> with message 'Error: Недействительная подпись - предоставленная подпись не совпала. [
> woocommerce_rest_authentication_error]' in .../vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php:324

Even if I try to get products with the query `$more_products = $woocommerce->get('products' , [ "in_stock" => false ]);` I catch the exception.

Actually when I pass `in_stock` as true, I get list of products, but all product both types  'in stock' and 'out of stock'.

**Comment by claudiosanches** [comment]
You just need to cache and exception and pass the correct data.
Still it is a response from WooCommerce REST API, not an issue on this library.
