### ISSUE TITLE
Syntax errors when BOM present

### ISSUE THREAD

**Issue by bryceadams** [woocommerce/wc-api-php#104]
Sometimes while making requests, it fails due to a syntax error. I've found this can be solved by removing the BOM (Byte Order Mark).

More on it here: http://stackoverflow.com/questions/17219916/json-decode-returns-json-error-syntax-but-online-formatter-says-the-json-is-ok

Ideally this would be handled at the PHP level in json decode but it isn't.

@claudiosanches I will PM you a URL as an example.

**Comment by Oldeu** [comment]
Hi,
a week ago I ran into the same issue and iI solved it the same way (exactly at 19/5/17). My code have run without a problem for weeks... So any ideas where this was coming from?
