### ISSUE TITLE
Create exact order copy via API

### ISSUE THREAD

**Issue by vasikgreif** [woocommerce/wc-api-php#106]
I'm trying to create exact copy of an order created on one e-shop to another e-shop.

Is there an easy way to do that? Currently I'm manually creating the array with addresses, items etc. when order is created on the first eshop, which works, but won't work with all the plugins.

**Comment by claudiosanches** [comment]
This repository is only for issues on this PHP library and not for questions related to how to use the WooCommerce REST API.
If you have questions you can always use https://wordpress.org/support/plugin/woocommerce
