### ISSUE TITLE
orders fatal error

### ISSUE THREAD

**Issue by johnwrise** [woocommerce/wc-api-php#107]
I try to post below array to orders, but there have an error :  Fatal error: Uncaught exception 'Automattic\WooCommerce\HttpClient\HttpClientException' with message 'Syntax error' in \wc-api-php-1.2.0\src\WooCommerce\HttpClient\HttpClient.php on line 340. 

I cannot find out what syntax error, please help, thanks.

Array
(
    [payment_method] => cash
    [payment_method_title] => Cash
    [status] => completed
    [customer_id] => 8
    [line_items] => Array
        (
            [0] => Array
                (
                    [product_id] => 256
                    [quantity] => 2
                )

        )

    [set_paid] => true
    [customer_note] => New member
    [meta_data] => Array
        (
            [0] => Array
                (
                    [key] => sh_transcation_storeId
                    [value] => 580c5da45c196d8304aa4986
                )

            [1] => Array
                (
                    [key] => sh_transcation_invoiceNumber
                    [value] => 0011610252045115
                )

        )

)

**Comment by claudiosanches** [comment]
Syntax error in the JSON response, so your server is throwing PHP warnings or fatal errors.
Have you fixed it on your server already?

Closing since is not an issue with this library.

**Comment by johnwrise** [comment]
for endpoint customers, products have no issue, only for orders have fatal error

**Comment by jlavnv** [comment]
$woocommerce->get('orders') still error, don't know if there is any way to fix it

**Comment by inpresif** [comment]
> $woocommerce->get('orders') still error, don't know if there is any way to fix it

Just checked, works fine on our end.

**Comment by jlavnv** [comment]
> > $woocommerce->get('orders') still error, don't know if there is any way to fix it
> 
> Just checked, works fine on our end.

Thanks for the feedback, I'm getting a JSON ERROR error like this. I'm investigating, but don't know what it is?
Automattic\WooCommerce\HttpClient\HttpClientException
JSON ERROR: Syntax error
