### ISSUE TITLE
Product attribute not set - similiar attribute names

### ISSUE THREAD

**Issue by grosssmutttr** [woocommerce/wc-api-php#109]
Hi there, 
I created two attributes terms which belong to the attribute "pa_farbe":
1. name: "white/black" which creates a slug "whiteblack"
2. name: "white/(black)" which creates a slug "whiteblack-2"

Now when I add a product via the api (v1) with:

```
$dataProduct = [
            'attributes' => [
                    [
                    'id' => 1,
                    'name' => 'Farbe',
                    'slug' => 'pa_farbe',
                    'visible' => false,
                    'variation' => true,
                    'options' => array("white/(black)")
                ]
            ]
        ];
```

It tries to add the whiteblack slug instead of the whiteblack-2 slug.
After digging around I think that the api sets the attribute after creating the slug from the given name. Because of that the sent data "white/(black)" becomes whiteblack and not whiteblack-2.

So the api shouldn't create a slug out of the sent data (sanitize_title?) instead it should look after the slug in the already existing attributes.
Something like that:
get_term_by( 'name', $sentApiNameField, 'pa_farbe')->slug

**Comment by claudiosanches** [comment]
This issue does not look related to this library, so better try the community support forum: https://wordpress.org/support/plugin/woocommerce
Thanks.

**Comment by grosssmutttr** [comment]
I thought this is the right plane for reporting Rest Api bugs? I don't think that the community could help me fixing a kernel bug?

**Comment by claudiosanches** [comment]
@grosssmutttr sorry, but this is the repository for the PHP library, not about WooCommerce REST API.
