### ISSUE TITLE
API Rate Limit, cURL error 28: Operation timed out

### ISSUE THREAD

**Issue by codelabstudios** [woocommerce/wc-api-php#110]
I notice that when I fire off multiple requests in a row, the API times out and doesn't work at all.

If I make just 1 request, the response is okay.

Is this intended behavior? How can I allow multiple requests to be fired off quickly at once.

**Comment by claudiosanches** [comment]
>  the API times out and doesn't work at all.
Does not sounds like an issue with this REST API wrapper, so I'm closing it.
Try a properly support channel for WooCommerce, like: https://wordpress.org/support/plugin/woocommerce
Good luck.
