### ISSUE TITLE
Invalid rest param meta_data

### ISSUE THREAD

**Issue by vasikgreif** [woocommerce/wc-api-php#111]
After update to WC3, my call for creating an order isn't working anymore, I end with the error `Invalid rest param meta_data`.

What is the correct way to pass custom order metadata so it gets saved with an order?

**Comment by claudiosanches** [comment]
Does not sounds like an issue with this REST API wrapper, so I'm closing it.
Try a properly support channel for WooCommerce, like: https://wordpress.org/support/plugin/woocommerce
Good luck.
