### ISSUE TITLE
unable to get user for WooCommerce

### ISSUE THREAD

**Issue by HadarShpivak** [woocommerce/wc-api-php#112]
hey, i got the following error:
An error occurred in the request and at the time were unable to send the consumer data.

when using the next url:
https://shpivak.co.il/wc-auth/v1/authorize?app_name=RetargetIM&user_id=130&scope=read&return_url=https://shpivak.co.il/wp-admin/admin.php%26page=rim_RetargetIM_Site_Settings&callback_url=https://retargetim.herokuapp.com/SETUP/WC?url=https://shpivak.co.il%26siteName=shpivak.co.il%26adminMail=hadar.shpivak@gmail.com%26timeZone=2%26storeCountry=IL

(the callback is sending to a server of mine, and the return url - to the site's admin, in a specific page)

The Callback receives the CK and CS ,
but on the WooCommerce API KEYS - I don't see the new user - which means - that when I try accessing the WC Store with the CK & CS I got - I get an error...

**Comment by claudiosanches** [comment]
Does not sounds like an issue with this REST API wrapper, so I'm closing it.
Try a properly support channel for WooCommerce, like: https://wordpress.org/support/plugin/woocommerce
Good luck.

**Comment by alanbukstein** [comment]
could you resolve this?
i have the same issue
