### ISSUE TITLE
always return 10 results

### ISSUE THREAD

**Issue by peratik** [woocommerce/wc-api-php#113]
I tried to get all products (17) by woocommerce rest API:

```
require_once('WooCommerce/vendor/autoload.php');

use Automattic\WooCommerce\Client;

$woocommerce = new Client(
    'http://***', 
    'ck_***', 
    'cs_*'
);

$results = $woocommerce->get('products', ['per_page'=>17]); 

var_dump($results);

```
But returns 10 results.

Please advice what is wrong?

We have 17 active products on our woocommerce website.

**Comment by claudiosanches** [comment]
Have you tried to read the documentation?
https://woocommerce.github.io/woocommerce-rest-api-docs/#pagination

**Comment by peratik** [comment]
Yes,

$results = $woocommerce->get('products', array('page'=>2));	 // Not working : first 10 restults

$results = $woocommerce->get('products', array('posts_per_page'=>20));	 // Not working : first 10 restults

$results = $woocommerce->get('products', array('per_page'=>2));	 // Not working  : first 10 restults

Please advice.

**Comment by claudiosanches** [comment]
Using WP REST API integration v2? or using legacy REST API v3?
Because in the legacy one is other doc that you need to check, but all linked at the same doc.
Not to mention that this is not an issue with this REST API library.

**Comment by peratik** [comment]
`$results = $woocommerce->get('products', array('filter[limit]'=>20));`

Finally Works!

**Comment by AizazMemon** [comment]
http://www.ajwa.com.pk/wp-json/wc/v1/products?&oauth_signature_method=HMAC-SHA1&oauth_consumer_key=ck_7a26a938a1b2563c4af5a5ff85b81a1f12636e3b&oauth_version=1.0&oauth_timestamp=1518423911&oauth_nonce=-196911576&oauth_signature=F%2F4V6O1dAteDWWN1EZOCQNuSv7k%3D&per_page=50
this not working for me i am trying to get more than 100 products but when i am adding per_page error occure 401 but same thing working well on postman

**Comment by Riujii** [comment]
Requests that return multiple items will be paginated to 10 items by default. This default can be changed by the site administrator by changing the posts_per_page option , 
this is changed in the wordpress in the menu> settings> reading> blog pages show at most, for me it works perfectly

**Comment by shrimpwagon** [comment]
This still does not work even after setting the "blog pages show at most"

**Comment by wpmkorg** [comment]
You can retrieve any number of product with this code

```
require_once('WooCommerce/vendor/autoload.php');

use Automattic\WooCommerce\Client;

$woocommerce = new Client(
    'http://***', 
    'ck_***', 
    'cs_*'
);

print_r($woocommerce->get( 'products', array('per_page'=>20) ));
```
its work for all, Thanks

**Comment by mujuonly** [comment]
@wpmkorg  Maximum 100 items can be retrieved?

**Comment by jhoanborges** [comment]
> @wpmkorg Maximum 100 items can be retrieved?

Yes . I'm trying to achieve this. I'm Currently using 'per_page'=>100.

**Comment by mujuonly** [comment]
> You can retrieve any number of product with this code
> 
> ```
> require_once('WooCommerce/vendor/autoload.php');
> 
> use Automattic\WooCommerce\Client;
> 
> $woocommerce = new Client(
>     'http://***', 
>     'ck_***', 
>     'cs_*'
> );
> 
> print_r($woocommerce->get( 'products', array('per_page'=>20) ));
> ```
> 
> its work for all, Thanks

Maximum 100 rows

**Comment by muhaiminulIslamIkhlas** [comment]
> > You can retrieve any number of product with this code
> > ```
> > require_once('WooCommerce/vendor/autoload.php');
> > 
> > use Automattic\WooCommerce\Client;
> > 
> > $woocommerce = new Client(
> >     'http://***', 
> >     'ck_***', 
> >     'cs_*'
> > );
> > 
> > print_r($woocommerce->get( 'products', array('per_page'=>20) ));
> > ```
> > 
> > 
> > its work for all, Thanks
> 
> Maximum 100 rows

please can help me to fetch all the products. I can get only 100 products by this. How to set page number. I am new to wordpress.

**Comment by muhaiminulIslamIkhlas** [comment]
I just need all the products

**Comment by mujuonly** [comment]
@muhaiminulIslamIkhlas  - Check this answer - https://stackoverflow.com/a/61460581/1117368
