### ISSUE TITLE
Add images to product gallery

### ISSUE THREAD

**Issue by scriptburn** [woocommerce/wc-api-php#116]
Suppose I have a product and i want to assign 10 images to this product gallery , now if i use create product api and add all 10 images in array i get curl timeout error due to the fact it takes time for wp to download the images from url and process them .

So is there any way that i can assign images to product gallery one by one after i created the product?

i tried updating the product with 10 images array but i get error 
Error: #0 is an invalid image ID. [woocommerce_product_invalid_image_id]  

so i was wondering is there any way to do this ? add images to product one by one ?

**Comment by claudiosanches** [comment]
Does not sounds like an issue with this REST API wrapper, so I'm closing it.
Try a properly support channel for WooCommerce, like: https://wordpress.org/support/plugin/woocommerce
Good luck.
