### ISSUE TITLE
Seems to break a filtered call

### ISSUE THREAD

**Issue by rokdevil** [woocommerce/wc-api-php#118]
If I want to filter on created_at_min the url call looks like:

**/orders?filter[created_at_min]=2017-01-01**

However, passing the filter as an array to your Client->get call:

`$wc = new Client(
	$url, 
	$key, 
	$secret, 
	[
		'wp_api'=>true,
		'version'=>'wc/v1'
	]
);`
`$params = [ 
						'filter' => [
							'created_at_min' => $min_date
						]
					];`
`
$wc->get("orders", $params);
`

This ends up url-encoding the brackets in HttpClient.php@buildUrlQuery.

I updated my local version to:

`$url .= '?' . \urldecode(\http_build_query($parameters));`

which seems to correct the issue.

**Comment by jaggedsoft** [comment]
Perhaps this is just a documentation issue.
`$wc->get('orders',['page'=>$page,'filter[order]'=>'asc']);`
You have to provide it as a string with brackets, not another array

**Comment by claudiosanches** [comment]
This has been fixed in 1.3.0.
