### ISSUE TITLE
How to add custom field to shipping info of user

### ISSUE THREAD

**Issue by TranQuangMinh** [woocommerce/wc-api-php#119]
Hi.
I want add field Phone and Email to shipping info of user, But I did not find any guidance for this issue.
Please help me. Thanks

**Comment by claudiosanches** [comment]
This repository is for issues with WooCommerce REST API PHP library only, not general support.

**Comment by TranQuangMinh** [comment]
Thank @claudiosanches, i know but i working with WooCommerce REST API PHP.

**Comment by claudiosanches** [comment]
Ok if you are using this PHP library, just make questions about this library and I can answer, but not questions about the WooCommerce REST API, for it you can use the forum on WordPress.org.
