### ISSUE TITLE
Cannot redeclare class OAuth

### ISSUE THREAD

**Issue by HuberStefan** [woocommerce/wc-api-php#121]
Hi,
i always get this error when i use the rest-api-client:

Fatal error: Cannot redeclare class OAuth in /HttpClient/OAuth.php on line 16

Client Configuration:
require_once 'WooCommerce-Api/Client.php';

$client = new Client(
        "https://.../", "ck_...", "cs_..", [
    'version' => 'wc/v1',
    'ssl_verify' => false,
    'timeout' => 25
        ]
);

The Kloon Rest-Api-Client Libary works perfect with the same configuration.
https://github.com/kloon/WooCommerce-REST-API-Client-Library

But i wil use this api.
Can anybody help me?

Thanks in advance

Regards
Stefan

**Comment by claudiosanches** [comment]
> The Kloon Rest-Api-Client Libary works perfect with the same configuration.
It's a whole different library without anything related with this one here...

> Fatal error: Cannot redeclare class OAuth in /HttpClient/OAuth.php on line 16

Just use composer autoload and will be just fine.
