### ISSUE TITLE
woocommerce rest api version v2 #in_stock 

### ISSUE THREAD

**Issue by vandan-noesis** [woocommerce/wc-api-php#123]
$param = array("in_stock"=> true,"category" => "182" , "min_price" => "500" , "max_price" => "1000" );
$result = $woocommerce->get('products',$param);

The result that i receive is not in the price range.

I am using woocommerce php client VERSION = '1.2.0'.

If i remove instock i get the desired result in the given price range.

Please let me know where i am wrong.

**Comment by claudiosanches** [comment]
Does not sound like an issue with this REST API library, since who controls the results is WooCommerce, so you should try a WooCommerce support channel, like: https://wordpress.org/support/plugin/woocommerce
