### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by PizzalaFlorian** [woocommerce/wc-api-php#125]
Hello,
I used the Rest api on my website with CakePHP during one month with no issue, and this morning i see this error :
"Syntax error
Automattic\WooCommerce\HttpClient\HttpClientException"

I try to debug it, but i don't understand my error, can you help me ?

there is my code :

$woocommerce = new Client(
'https://www.mywebsite.fr/', 
 'ck_xxxxxxxxxxxxxxxxxxxxxxxxx',
 'cs_xxxxxxxxxxxxxxxxxxxxxxxxx',
  [
    'wp_api' => true,
    'version' => 'wc/v2',
     'query_string_auth' => true
 ]
 );

try {
        $wooProduct = $woocommerce->get('products',['sku' => $myProduct['sku']]);
 } catch (HttpClientException $e) {
        $e->getMessage(); // Error message.
        $e->getRequest(); // Last request data.
        $e->getResponse(); // Last response data.
 }

I check myProduct variable , it's ok, But cakePhp debuguer only show me an syntaxe error on $wooProduct = $woocommerce->get('products',['sku' => $myProduct['sku']]);

There is something wrong with my code ? Or this error is link to a server error ?
Thank you

**Comment by PizzalaFlorian** [comment]
Sorry i found my error, it was a conflic with Wordfence, a Security plugin who block the api.

**Comment by ChristianGerdes** [comment]
How did you exactly solve the problem, @PizzalaFlorian ? I use Wordfence too and get the same error.

**Comment by PizzalaFlorian** [comment]
Hello @ChristianGerdes. 
You need to add your own ip-adresse in the wordfence white-list, I don't know why but the ip was different for my merchant web site and my site on cakephp ( XXX.XXX.XXX.2 and XXX.XXX.XXX.9). I see my "ban" request on the wordpress live traffic, and copy my ip on the white list. After that, it work very well.
