### ISSUE TITLE
Filter Parameters api

### ISSUE THREAD

**Issue by eros2187** [woocommerce/wc-api-php#126]
Hi I'm having trouble setting up a call to get the detail of the product by id;
And apply the first limit filter

How do I have to set the call to have a product's array for id?  And the limit call?

For example, and a call to have a list of products by category.
($woocommerce->get('products',$parameters = ['category' => $id]))

**How do I have to set the call to have a product's array for id?** 
($woocommerce->get('products',$parameters = ['id' => $id])) ??

**And apply the first limit filter??**
($woocommerce->get('products',$parameters = ['limit' => 50])) ??

If there is an example of documentation I would appreciate
thank you

**Comment by claudiosanches** [comment]
Your questions sounds related to the WooCommerce REST API and not about this library.
You can find the docs here: https://woocommerce.github.io/woocommerce-rest-api-docs/ and use the support channel in https://wordpress.org/support/plugin/woocommerce

> How do I have to set the call to have a product's array for id?
In the docs you can find it.

> And apply the first limit filter??
It's just an array, so you can work with it like any other array in PHP.

**Comment by eros2187** [comment]
OK thanks!
  I wanted to ask you a question to be able to create my own app linked to woocomerce that library should I use? You can show me a thank you!

What is your library for that purpose to use?

thank you

**Comment by claudiosanches** [comment]
@eros2187 you can create apps with any programming language, so feel free to create your app with this library or pick the language your prefer.
