### ISSUE TITLE
Per_page bug

### ISSUE THREAD

**Issue by namanix** [woocommerce/wc-api-php#127]
There seems to be a bug when i'm trying to get all the categories in woocommerce.
When i do this: 
`$woocommerce->get('products/categories', ['per_page' => 10000]);`
i get: **Error: Ongeldige parameter(s): per_page [rest_invalid_param]**
But when i for example use a page parameter like this: 
`$woocommerce->get('products/categories', ['page' => 2]);`
it works perfectly. Why can't i use per_page? It is part of the docs:
http://woocommerce.github.io/woocommerce-rest-api-docs/?php#list-all-product-categories

Hope someone can help me with this issue

Kind regards,
Kevin Walter

**Comment by claudiosanches** [comment]
What REST API version are you using?
Because depending on the version there is no `per_page` parameter.

This sounds like you are not using the correct REST API docs for the version you are trying to use from the REST API, not to mention that this is not an issue with this REST API library.

**Comment by shenopkss** [comment]
@namanix 
I use php library `"automattic/woocommerce": "^1.3"` https://github.com/woocommerce/wc-api-php

The request is successful:
```
$woocommerce->get('products/categories',[
    'page' => 1,
    'per_page' => 100, // if per_page > 100，Error: Invalid parameter(s): per_page [rest_invalid_param]
]);
```
Don't thank me. My name is 雷锋.

**Comment by AizazMemon** [comment]
http://www.ajwa.com.pk/wp-json/wc/v1/products?&oauth_signature_method=HMAC-SHA1&oauth_consumer_key=ck_7a26a938a1b2563c4af5a5ff85b81a1f12636e3b&oauth_version=1.0&oauth_timestamp=1518423911&oauth_nonce=-196911576&oauth_signature=F%2F4V6O1dAteDWWN1EZOCQNuSv7k%3D&per_page=50
this not working for me i am trying to get more than 100 products but when i am adding per_page error occure 401 but same thing working well on postman

**Comment by tallcoder** [comment]
Wow ... not a single helpful answer.

**Comment by tallcoder** [comment]
In case this helps save anyone sometime in the future, when you are calling "per_page" on the products/categories endpoint, the MAX you can use is 100. 

Anything more then that will cause the error `Error: Invalid parameter(s): per_page [rest_invalid_param]`
