### ISSUE TITLE
WooCommerce REST API not working 

### ISSUE THREAD

**Issue by mamataadsul** [woocommerce/wc-api-php#129]
We are receiving nothing while working on REST API v2 version of WooCommerce. It was working fine when we are retrieving data from localhost which is http but now we have uploaded it to the server which is https. we have also clear the cache of wordpress. Still getting

stdClass Object
(
    [errors] => Array
        (
            [0] => stdClass Object
                (
                    [code] => woocommerce_api_authentication_error
                    [message] => Invalid Timesatmp
                )

        )

) 
How can we covert the timestamp to server timestamp in the code Here is the function from where the timesatmp is generating 
public function get_oauth_params( $params, $method ) {

		$params = array_merge( $params, array(
			'oauth_consumer_key'     => $this->consumer_key,
			'oauth_timestamp'        => time(),
			'oauth_nonce'            => sha1( microtime() ),
			'oauth_signature_method' => 'HMAC-' . self::HASH_ALGORITHM,
		) );

		// the params above must be included in the signature generation
		$params['oauth_signature'] = $this->generate_oauth_signature( $params, $method );

		return $params;
	}

**Comment by claudiosanches** [comment]
You can define your own timestamp to match with your server timezone: https://github.com/woocommerce/wc-api-php#client-options

**Comment by mamataadsul** [comment]
Hello  claudiosanches,

Thanks for the response.

We have tried everything, we change the timestamp according to the server which is American/LosAngeles as you can see in the below code but still we are facing the same issue as Invalid Timestamp.

$date = new DateTime(null, new DateTimeZone('America/Los_Angeles'));
echo 'America/New_York: '.$date->getTimestamp().'<br />'."\r\n";

$woocommerce = new Client(
    'url',
        'cusumer_key',
        'secret_key',
    [
               'wp_api' => true,
               'version' => 'wc/v2',
               'timeout'=>30,
               'verify_ssl'=>false,
               'query_string_auth'=>true,
               'oauth_timestamp'=>$date->getTimestamp(),

    ]
);
    // index
  //echo "<pre>";print_r($woocommerce);exit;
    $results = $woocommerce->get('customers');
  echo "<pre>";print_r($results);exit;

**Comment by claudiosanches** [comment]
So still is not the same timezone.

**Comment by mamataadsul** [comment]
Hello claudiosanches,

Yes  after changing the time zone it is not working. We have checked it on our local server,  there we are not facing any issue but as it comes to the server we are not able to map it the timezone, Our server is on the PDT time with American/Los in California but still is was not working.

As you say it is the problem of the time zone after changing the timezone on the localhost it is working fine without any issue. We need some technical help here for how should we change the timezone so that it works. We have also tried the REST API without the composer the same problem we are facing there also  the outh_timesatmp=>time() in the http request class. Is the problem is because the server has https and the wordpess site is on http. We have also tried all other parameter as verify_ssl and debug, timeout. Still not work. Please help.

**Comment by claudiosanches** [comment]
If the server uses HTTPS you can just avoid use oAuth1.0 and will have no problem with timezones.
Still for what you are reporting does not sounds like an issue with this library, but a problem with the configuration that you are using.

**Comment by mamataadsul** [comment]
Thanks for the response.

We are trying to use your API from our HTTPS server which is in  'America/Los_Angeles' time stamp to our wordpress store in HTTP we have changed the timestamp as you mentioned  [https://github.com/woocommerce/wc-api-php#client-options ] but still we get Invalid Timestamp error. 
But when we try to connect HTTPS to Wordpress store with SSL it is connecting without any error. In code there is a function which check for ssl(is_ssl) if it is HTTPS then it doesn't pass timestamp but if it is coming from the HTTP it passes the timesatmp .

We have also made the is_ssl parameter as true and also changes the timestamp to our server which is PST but still not able to connect. If it is not issue of the libraray then it should get connected without any error whether it as HTTPS to HTTP, HTTPS to HTTPS and HTTP to HTTP. 

Please help.

**Comment by claudiosanches** [comment]
Just use Basic Auth then, using HTTPS, since does not display any error.

**Comment by mamataadsul** [comment]
Your API will not work on http store URL?

**Comment by mamataadsul** [comment]
So it means that API is not working on the HTTP severs it works only for the HTTPS server because it doesnot support the timestamp changes.

**Comment by mamataadsul** [comment]
Then the issue shouldn't be closed because it a problem in the API.

**Comment by claudiosanches** [comment]
WooCommerce REST API works just with on HTTP servers, but what I'm saying here is that this is not an issue with this library and you should look for a proper support channel like: https://wordpress.org/support/plugin/woocommerce
