### ISSUE TITLE
Create a product: Call to undefined function Automattic\\WooCommerce\\HttpClient\\json_last_error()

### ISSUE THREAD

**Issue by greatplateau** [woocommerce/wc-api-php#130]
When I create a product:
$woocommerce->post('products', $data);

``
PHP Fatal error:  Uncaught Error: Call to undefined function Automattic\\WooCommerce\\HttpClient\\json_last_error() in /var/www/html/wordpress/wp-content/plugins/testplugin/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php:344\nStack trace:\n#0 /var/www/html/wordpress/wp-content/plugins/testplugin/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php(385): Automattic\\WooCommerce\\HttpClient\\HttpClient->processResponse()\n#1 /var/www/html/wordpress/wp-content/plugins/testplugin/vendor/automattic/woocommerce/src/WooCommerce/Client.php(56): Automattic\\WooCommerce\\HttpClient\\HttpClient->request('products', 'POST', Array)\n#2 /var/www/html/wordpress/wp-content/plugins/testplugin/testplugin.php(83): Automattic\\WooCommerce\\Client->post('products', Array)\n#3 /var/www/html/wordpress/wp-content/plugins/testplugin/testplugin.php(45): test_convert(33)\n#4 /var/www/html/wordpress/wp-content/plugins/testplugin/testplugin.php(19): test_handle_post()\n#5 /var/www/html/wordpress/wp-includes/class-wp-hook.php(298): in /var/www/html/wordpress/wp-content/plugins/testplugin/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php on line 344, referer: http://localhost/wordpress/wp-admin/admin.php?page=test-plugin
``

**Comment by thetre97** [comment]
similarly, I have the below issue when trying to list products.
```
Fatal error: Uncaught exception 'Automattic\WooCommerce\HttpClient\HttpClientException' with message 'unexpected character' in /home/ubuntu/workspace/woo/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php on line 346 Automattic\WooCommerce\HttpClient\HttpClientException: unexpected character in /home/ubuntu/workspace/woo/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php on line 346 Call Stack: 0.0006 233776 1. {main}() /home/ubuntu/workspace/woo/woo.php:0 0.0014 271920 2. Automattic\WooCommerce\Client->get() /home/ubuntu/workspace/woo/woo.php:17 0.0014 272424 3. Automattic\WooCommerce\HttpClient\HttpClient->request() /home/ubuntu/workspace/woo/vendor/automattic/woocommerce/src/WooCommerce/Client.php:82 0.2385 299336 4. Automattic\WooCommerce\HttpClient\HttpClient->processResponse() /home/ubuntu/workspace/woo/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php:385
```

**Comment by greatplateau** [comment]
Hi thetre97,

Your issue 'unexpected character' looks different from mine. Mine is undefined function json_last_error().

**Comment by claudiosanches** [comment]
You should have http://php.net/manual/en/function.json-last-error.php disabled.

**Comment by Marycka9** [comment]
Disable it:

`define('EOL', (PHP_SAPI == 'cli') ? PHP_EOL : '<br/>');`
