### ISSUE TITLE
problem in put method

### ISSUE THREAD

**Issue by sahandmax** [woocommerce/wc-api-php#131]
hi all of my methods working but when i'm using 'put' i gived this response

my code 
`$woocommerce_api_v2 = new Client(
    'http://XXXXXX', 
    'ck_XXXXXX', 
    'cs_XXXXXX',
    [
        'wp_api' => true,
        'version' => 'wc/v2',
		'timeout' => -1
    ]
);
if ($_GET['req'] == "product_update") {
	$data = [
    'price' => $_GET['price'],
	'in_stock' => $_GET['in_stock']
	];
	
	print_r($woocommerce_api_v2->put('products/'.$_GET['id'], $data));
}`

i gived this response

Fatal error: Uncaught Automattic\WooCommerce\HttpClient\HttpClientException: cURL Error: Empty reply from server in C:\xampp2\htdocs\takmallapi\vendor\automattic\woocommerce\src\WooCommerce\HttpClient\HttpClient.php:380 Stack trace: #0 C:\xampp2\htdocs\takmallapi\vendor\automattic\woocommerce\src\WooCommerce\Client.php(69): Automattic\WooCommerce\HttpClient\HttpClient->request('products/14977', 'PUT', Array) #1 C:\xampp2\htdocs\takmallapi\index.php(46): Automattic\WooCommerce\Client->put('products/14977', Array) #2 {main} thrown in C:\xampp2\htdocs\takmallapi\vendor\automattic\woocommerce\src\WooCommerce\HttpClient\HttpClient.php on line 380

thank you for helping me
only put receives this

**Comment by claudiosanches** [comment]
This is the error:

> URL Error: Empty reply from server

Your server is not returning anything, for sure blocking PUT requests.

Closing since is not an issue with this REST API wrapper.
