### ISSUE TITLE
woocommerce_rest_authentication_error

### ISSUE THREAD

**Issue by alanbukstein** [woocommerce/wc-api-php#133]
Hi, i am getting this response trying to access to any api. I am using V1
`{
    "code": "woocommerce_rest_authentication_error",
    "message": "La clave de cliente no es válida.",
    "data": {
        "status": 401
    }
}`

**Comment by sohanyugasa** [comment]
Hi Guys!
I am also getting the same error. Anyone could suggest the better solution for this one error.
Thanks.

**Comment by MiBi-Tech** [comment]
Anyone got any solution?

**Comment by MiBi-Tech** [comment]
@alanbukstein @sohanyugasa  have you tried .htaccess

`header set Access-Control-Allow-Origin "*"
header set Access-Control-Allow-Headers "origin,content-type,user-agent, accept, x-r$"
header set Access-Control-Allow-Methods "PUT,GET,POST,DELETE,OPTIONS,HEAD"
`
