### ISSUE TITLE
before and after not working as expected

### ISSUE THREAD

**Issue by cgsmith** [woocommerce/wc-api-php#135]
I am trying to get the following code to work properly but there seems to be a disconnect between the documentation or something upstream.

Take this first example. It resorts in about 7 orders that range back to July 26, 2017 to today August 3rd, 2017.
```php
$api = new Client(
    $config['ecommerce']['api_url'],
    $config['ecommerce']['api_key'],
    $config['ecommerce']['api_secret'],
    [
        'query_string_auth' => true,
    ]
);

$dt = new \DateTime('yesterday');
$params = [
    'before' => $dt->setTime(23,59,59)->format(DATE_ISO8601), // date must be ISO 8601
    'after' => $dt->setTime(0,0,0)->format(DATE_ISO8601),
];
$orders = $api->get('orders', $params);
```

Secondly, take this example. It fails on the parameters even though the date is in ISO8601 format.
```php
$api = new Client(
    $config['ecommerce']['api_url'],
    $config['ecommerce']['api_key'],
    $config['ecommerce']['api_secret'],
    [
        'query_string_auth' => true,
        'wp_api' => true,
        'version' => 'wc/v2'
    ]
);

$dt = new \DateTime('yesterday');
$params = [
    'before' => $dt->setTime(23,59,59)->format(DATE_ISO8601), // date must be ISO 8601
    'after' => $dt->setTime(0,0,0)->format(DATE_ISO8601),
];
$orders = $api->get('orders', $params);
```

Finally, in order to get the proper orders to pull through - just yesterdays orders. I have to write the code this way.
```php

$api = new Client(
    $config['ecommerce']['api_url'],
    $config['ecommerce']['api_key'],
    $config['ecommerce']['api_secret'],
    [
        'query_string_auth' => true,
        'wp_api' => true,
        'version' => 'wc/v2'
    ]
);

$dt = new \DateTime('yesterday');
$params = [
    'before' => $dt->setTime(23,59,59)->format("Y-m-d\TH:i:s"), // date must be ISO 8601
    'after' => $dt->setTime(0,0,0)->format("Y-m-d\TH:i:s"),
];
$orders = $api->get('orders', $params);
```

I am opening this issue in the hopes that either this can be fixed at the API level or upstream at the WordPress level.

**Comment by claudiosanches** [comment]
> I am opening this issue in the hopes that either this can be fixed at the API level or upstream at the WordPress level.

Thanks, but really is not something that we can fix on this REST API library.

**Comment by cgsmith** [comment]
@claudiosanches How? Where can it be fixed? I am more than willing to submit a PR to address the scenario.

**Comment by claudiosanches** [comment]
@cgsmith on WordPress trac, since WooCommerce does the same as WordPress core.
https://core.trac.wordpress.org/
