### ISSUE TITLE
per_page Fatal error on list all orders

### ISSUE THREAD

**Issue by cgsmith** [woocommerce/wc-api-php#136]
On the api call `GET orders` this fails:

```php
$params = [
            'before' => $dt->setTime(23,59,59)->format("Y-m-d\TH:i:s"), 
            'after' => $dt->setTime(0,0,0)->format("Y-m-d\TH:i:s"),
            'per_page' => 1000
        ];
```

**Error Seen**: Fatal error: Uncaught Automattic\WooCommerce\HttpClient\HttpClientException: Error: Invalid parameter(s): per_page [rest_invalid_param]

**Expectation**: documentation should be updated to remove per_page if it is not relevant or provide example.

*Note*: `wp_api => true`

**Comment by willfaulds** [comment]
did you make any progress with this? I seem to be suffering an issue that this might effect

**Comment by willfaulds** [comment]
hmmm really disappointing as each request adds substantial loadtime - making serious app development impractical

**Comment by jonathan-bird** [comment]
+1 to this

**Comment by claudiosanches** [comment]
```
'per_page' => 1000
```

WooCommerce REST API only allow max of `100` results per page.
That's why the problem.
And please not that this is not something that we can control on this REST API library.

**Comment by cgsmith** [comment]
@claudiosanches Does the issue belong somewhere else? I did not find any WooCommerce documentation related to 100 results per page. Can you link to that?

**Comment by claudiosanches** [comment]
@cgsmith it's the same behavior from WordPress REST API (they have it documented for sure), not to mention that you can read about it checking the schema with `OPTIONS /orders`.

**Comment by beppe9000** [comment]
I think a `getAll` method that handles pagination internally and returns an array of everything could be useful in these situations

**Comment by claudiosanches** [comment]
@beppe9000 Please feel free to submit a Pull Request. Thanks for your help.
