### ISSUE TITLE
API authentication error (Invalid signature) for include param with 10+ ids

### ISSUE THREAD

**Issue by willfaulds** [woocommerce/wc-api-php#139]
I have mostly got to grips with API but have an odd issue with only 1 order continually creating an exemption...

Caught exception: Error: Invalid signature - provided signature does not match. [woocommerce_rest_authentication_error]Caught exception:

The exact same code is working on 100s of other requests but will not complete on this specific one. I have double checked and cannot find anything unusual with the order and fear this might be a bug in the API wrapper?

Basic outline is API lookup the order->create an array of product ids->API lookup the products
```
$woocommerce->get('orders/'.$id);
...loop through etc...
$args = array(
  'include' => $orderProductIds,
);
$woocommerce->get('products', $args);
```

Request Headers:
{
```
    "accept": "application\/json",
    "host": "XXX",
    "user_agent": "WooCommerce API Client-PHP\/1.3.0"
}
```

Query Parameters (**oddly despite using array_values() in my code this shows "include" as an associate array - this is the only visible difference to other successful API calls - the code used to generate other successful calls is identical**
```
{
    "include": {
        "0": "74",
        "1": "70",
        "10": "81",
        "2": "75",
        "3": "77",
        "4": "73",
        "5": "137",
        "6": "85",
        "7": "89",
        "8": "88",
        "9": "79"
    },
    "oauth_consumer_key": "ck_b269e6a4023e2aa187a7e10d16e1b955efcaa715",
    "oauth_nonce": "32919da782d831bbe28a872f09868cf33a051af1",
    "oauth_signature": "y\/6DqS6ASxALHoY3yalSO9vXk\/e6Myk4bqbhXW9OjE8=",
    "oauth_signature_method": "HMAC-SHA256",
    "oauth_timestamp": "1503309405"
}
```

Response Headers
```
{
    "Content-Type": "application\/json; charset=UTF-8",
    "X-Robots-Tag": "noindex",
    "Link": "<http\/\/XXX\/wordpress\/wordpress\/wp-json\/>; rel="https\/\/api.w.org\/"",
    "X-Content-Type-Options": "nosniff",
    "Access-Control-Expose-Headers": "X-WP-Total, X-WP-TotalPages",
    "Access-Control-Allow-Headers": "Authorization, Content-Type"
}
```
Response Body
```
{
    "data": {
        "code": "woocommerce_rest_authentication_error",
        "message": "Invalid signature - provided signature does not match.",
        "data": {
            "status": 401
        }
    },
    "headers": [],
    "status": 401
}

```

**Comment by willfaulds** [comment]
I have tried creating a new API key and still, only this one list of products (generated from a successful order API call) fails...

**Comment by willfaulds** [comment]
@claudiosanches I *think* the problem is caused by passing more than 10 product ids in the limit param...

As a workaround I tried getting all orders instead (I need this working ASAP) however only 10 products were returned by the API. I then tried the _per_page_ param as documented here https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-products

But I get a 

> Caught exception: Error: Invalid parameter(s): per_page [rest_invalid_param]

Any ideas at all please as this is important to my use-case.

**Comment by claudiosanches** [comment]
Don't sound like an issue on this REST API library.
Since this library is not able to limit or change how WooCommerce or WordPress REST API does any kind of authentication.
