### ISSUE TITLE
Action "woocommerce_api_create_order" it's not triggered

### ISSUE THREAD

**Issue by nicomoka** [woocommerce/wc-api-php#141]
Hi,

I'm using this action (**woocommerce_api_create_order**) to take some actions when a new order is created through the API. But now I see that it's not working.
I can't use actions or filters using "wc-api-php"?

Thanks!!

**Comment by nicomoka** [comment]
This is the action:
http://hookr.io/plugins/woocommerce/3.0.6/actions/woocommerce_api_create_order/

**Comment by claudiosanches** [comment]
This do not sound like an issue with this REST API library and may should be report on WooCommerce core issue tracker.
Thanks.
