### ISSUE TITLE
WooCommerce REST API returning same customer on 2 different pages.

### ISSUE THREAD

**Issue by Ahmdrza** [woocommerce/wc-api-php#143]
I'm getting customers list using following code:
`$wooObj->get('customers?page=$page //$wooObj is woocommerce object`
but on page 10 and 11 I am getting same customer that is causing issue while inserting in db as customer id should be unique but it returns two same ids which are breaking my program.
Any help??

**Comment by claudiosanches** [comment]
This REST API library can't control what WooCommerce return in the REST API results.
Better you try a WooCommerce support channel.
Thanks.
