### ISSUE TITLE
getting syntax error in wordpress 4.8.1 and woocommerce 3.1.2

### ISSUE THREAD

**Issue by mohammadlom** [woocommerce/wc-api-php#144]
I got syntax error in my Laravel application and when i try to catch exception and messages and response i got  the following response:
 object(Automattic\WooCommerce\HttpClient\Response)#618 ....
It's a large string for this object
I use my Laravel application in no ssl url and my store in url that have ssl(https)

any one can help me through this?
sorry for my bad English!

**Comment by claudiosanches** [comment]
Well, this don't sound like an issue with this REST API library... And there is already an example of how catch exceptions from this library, but is the same way that you'll catch exceptions for anything on PHP, I don't see anything that could cause problems or be different using Laravel.
