### ISSUE TITLE
How to add Product to the cart

### ISSUE THREAD

**Issue by ajayghaghretiya** [woocommerce/wc-api-php#147]
Hello, 
How to add the products to the cart by the rest API and how I update the quantity for it .. and how to get all the products listing from the cart of the particular user.

Is there any default API for it ?

**Comment by claudiosanches** [comment]
Hi there! GitHub is for reporting bugs and issues specific to the REST API PHP library for WooCommerce REST API. This is not a support portal.

If you need support with the REST API you should try https://wordpress.org/support/plugin/woocommerce

But there is no cart endpoint, you should manage the cart on your app and after it send to the orders endpoint to register the order on WooCommerce.
