### ISSUE TITLE
500er Error on POST Request

### ISSUE THREAD

**Issue by rorych** [woocommerce/wc-api-php#148]
Hi there

I would like to use the WooCommerce REST API with this cool Method - heads up a huge Thanks for the aweseome implementation, i love is, so slick!

But i'm struggling with the Code somehow.
Not shure if this is the right channel to mention this, but i can't figure it out and i'm not shure if it's a bug or a code error.

I'm trying to add a user.
First of all, with Postman POST and the direct cURL command on the CLI attempt i could add a user no problem, so the keys and the shop seem to work fine, it's this method that is not working for me, although it would be the cleanest.

So i build the $data Array and generate the $woocommerce object.
But when i try and post the array, i end up with a 500er Error and no feedback on what is wrong.

This is my Code:

```php
require __DIR__ . '/../../vendor/autoload.php';
use Automattic\WooCommerce\Client;
$woocommerce = new Client(
    'https://www.mydomain.ch/shop/', 
    'ck_mykey', 
    'cs_mykey',
    [
        'wp_api' => true,
        'version' => 'wc/v2',
    ]
);
```
this is the object, before i call the post method:
```
Automattic\WooCommerce\Client Object
(
    [http] => Automattic\WooCommerce\HttpClient\HttpClient Object
        (
            [ch:protected] => 
            [url:protected] => https://www.mydomain.ch/shop/wp-json/wc/v2/
            [consumerKey:protected] => ck_mykey
            [consumerSecret:protected] => cs_mykey
            [options:protected] => Automattic\WooCommerce\HttpClient\Options Object
                (
                    [options:Automattic\WooCommerce\HttpClient\Options:private] => Array
                        (
                            [wp_api] => 1
                            [version] => wc/v2
                        )

                )

            [request:Automattic\WooCommerce\HttpClient\HttpClient:private] => 
            [response:Automattic\WooCommerce\HttpClient\HttpClient:private] => 
            [responseHeaders:Automattic\WooCommerce\HttpClient\HttpClient:private] => 
        )

)
```

this is the call i make:
```php
print_r($woocommerce->post('customers', $data), true);
```

What am i doing wrong or is there a issue here?
Thanks in advance

**Comment by rorych** [comment]
Okay so it was my mistake, i just testet all again and i noticed a missing parameter (but also in the documentation of this feature in the API Docs) the password.
With adding it, it is now working.
Sorry for my Post - you can delete it if you want (i can't, i can only edit)

**Comment by RT-TL** [comment]
@rorych I seem to have the same issue. As you said the docs don't mention any password. Can you add more details on what you have done and what worked?
