### ISSUE TITLE
List all products 

### ISSUE THREAD

**Issue by nzshumate** [woocommerce/wc-api-php#150]
What is the best way to retrieve all products via the API? 

I am currently using  `$woocommerce->get('products', ['per_page'=>100]);` to fetch products, but changing the per_page param to a higher number will not allow more than 100 objects to be returned in the response. 

I am trying to avoid iterating through all of the pages, is there something I am missing here, or is this a limitation.

**Comment by strarsis** [comment]
@nzshumate: I also encountered this issue - and I solved it by using a do-while loop, requesting next 100 items (max amount per request) and array_merging them until the resulting product array is empty (then there are no further products to be fetched).

**Comment by claudiosanches** [comment]
This is a channel for questions about the PHP library only, if you have questions about the WooCommerce REST API you should use the support forum: https://wordpress.org/support/plugin/woocommerce
Thanks.

**Comment by alin0908** [comment]
Why would you close the thread since it's a PHP & API issue? @claudiosanches have a kit kat mate. there are a lot of people needing an answer at this question including me and woo documentation sucks at this chapter.

**Comment by claudiosanches** [comment]
@alin0908 sorry, but if it's an issue with WooCommerce REST API we should use the correct forum for that, especially this kind of question that there's will be useful for all users, not only for those using this library. If it's an issue with this PHP library I'm happy to reply here.
