### ISSUE TITLE
Option follow_redirects

### ISSUE THREAD

**Issue by olanko** [woocommerce/wc-api-php#153]
Hi!

Does option follow_redirects actually do anything? I can't find any references to that in source code.

Function lookForErrors() in HttpClient.php gives back an error with error code 302.

How should this work?

Greetings from Finland,
-Olli

**Comment by claudiosanches** [comment]
You can check the code here:
https://github.com/woocommerce/wc-api-php/pull/140/files

If is not working for you, please feel free to submit a Pull Request.

Just note how PHP do it:

![screenshot from 2018-01-12 14-59-41](https://user-images.githubusercontent.com/1264099/34886130-3db118b4-f7a9-11e7-9cb1-c7eadeaa098d.png)
