### ISSUE TITLE
Get order doesn't return any meta_data for line_items

### ISSUE THREAD

**Issue by swina** [woocommerce/wc-api-php#155]
Woocommerce 3.2.5
API Client: updated

I tried u**sing V1** and meta data are returned correctly (wp-json/wc/v1/orders/xxx): 
...
 "line_items": [
        {
            ....
            "total": "50.00",
            "total_tax": "0.00",
            "taxes": [],
            "meta": [
                {
                    "key": "pa_misura",
                    "label": "Misura",
                    "value": "XS"
                },
                {
                    "key": "pa_colore",
                    "label": "Colore",
                    "value": "Nut Brown"
                }
            ]
        }
    ],

**Using V2 (wp-json/wc/v2/orders/xxx)**
....
"line_items": [
        {
           ...
            "total": "50.00",
            "total_tax": "0.00",
            "taxes": [],
            "meta_data": [
                {},
                {},
                {}
            ],
            "sku": "030120-XS",
            "price": 50
        }
    ],

**Comment by Mr-AjayM** [comment]
Can we calculate the tax when creating orders via V1 or V2?

**Comment by claudiosanches** [comment]
Your question is lot related to this REST API library.
So I'm closing it.
