### ISSUE TITLE
Retrieves Orders List of Particular user By Rest API

### ISSUE THREAD

**Issue by Mr-AjayM** [woocommerce/wc-api-php#156]
I have tried to retrieves all the orders of the particular by the woocommerce rest API V2.
I have also read the documentation Of the WooCommerce REST API. There are the customer_id in Orders Properties. So, I have tried to retrieves all Orders by "customer_id" request. I have used the GET method the used URL: "/wp-json/wc/v2/orders".
But it returns all orders.

If Anyone has a solution for this issue Please share with me.

**Comment by chandra10207** [comment]
This topic is closed, but I don't find any solution here.
To return all order by a particular customer, use this endpoint
endpoint: /wp-json/wc/v2/orders?customer=9
here, 9 is the customer ID.

**Comment by Hamidaraghi** [comment]
Try this:

//_id_ is your customer id.
this.WooCommerce.getAsync('customers/_id_/orders/').then((data)=>{

        console.log(data.body);
      });

**Comment by avsinghan** [comment]
this works TYSM
/wp-json/wc/v2/orders?customer=9

**Comment by TyagrajBhatt** [comment]
But when i enter wrong user id then its returning blank array like this   [ ]

**Comment by ShujaShah** [comment]
how do i dynamically get the orders of the logged in user??

**Comment by aroolinks** [comment]
This worked for me, I fetched the data in postman through this
I intended to use this in my react app and it is working fine.. [woocommerce to react native ]
 .../wp-json/wc/v2/orders?customer=9

**Comment by AKRehmanKhan** [comment]
/wp-json/wc/v2/orders?customer=9    This endpoint is valid even with new version v3

**Comment by AjeetV-DTL** [comment]
localhost/wordpress/wp-json/wc/v3/orders?customer=2

**Comment by os3albert** [comment]
> localhost/wordpress/wp-json/wc/v3/orders?customer=2

it worked for me thanks
