### ISSUE TITLE
Variation not added

### ISSUE THREAD

**Issue by strarsis** [woocommerce/wc-api-php#157]
I try to add a variation to a product.

The following array is used for `Automattic\WooCommerce\Client` 
(`2453` is the ID of the product):

```php
Array
(
    [0] => Array
        (
            [id] => 2453
            [variations] => Array
                (
                    [0] => Array
                        (
                            [sku] => 4b8fb1f80ccc-100g
                            [regular_price] => 4.6
                            [weight] => 0.1
                            [attributes] => Array
                                (
                                    [0] => Array
                                        (
                                            [name] => Amount
                                            [option] => 100g
                                        )

                                )

                        )

                )

        )
);
````

```php
try {
    $woocommerce->post('products/batch', array('update' => $batch_updates));
  } catch (HttpClientException $e) {
    echo 'Error: ' . "\n";
    print_r($e->getMessage());  // Error message.
    print_r($e->getRequest());  // Last request data.
    print_r($e->getResponse()); // Last response data.
  }
````

POST just runs through correctly, no notices, warnings or errors.
But no variations have been added, nothing changed.

The product to be updated is a variable product with the attribute added.
Other modifications using the WooCommerce REST API work fine, just adding variations does not.

**Comment by strarsis** [comment]
Apparently the `prepare_object_for_database` method doesn't handle variation arrays at all, see code:
https://github.com/woocommerce/woocommerce/blob/master/includes/api/class-wc-rest-products-controller.php#L668

**Comment by claudiosanches** [comment]
Not an issue with this REST API wrapper.
You just forget to read the REST API docs for the version that you are trying to use.
Since the file you post here is from our REST API v2, that does not allow creating variations on the products endpoint, instead of it, you should post into the `wp-json/wc/v2/products/<id>/variations`.

**Comment by strarsis** [comment]
@claudiosanches: This complicates and slows down everything a lot because the variations have to be fetched from each product first, which takes much more time than just updating them as array in a product update.

**Comment by claudiosanches** [comment]
@strarsis still not an issue with this REST API library.

**Comment by maulikmakwana** [comment]
You can use variations/batch and used your existing product attributes
/wp-json/wc/v3/products/<product_id>/variations/batch
![varition](https://user-images.githubusercontent.com/3139719/73753208-5414e000-4788-11ea-93ea-ebd286902a4c.png)
