### ISSUE TITLE
Is there any way to Payment using REST API?

### ISSUE THREAD

**Issue by Mr-AjayM** [woocommerce/wc-api-php#161]
I am using the WooCommerce REST API for the Mobile APP development. I want to Integrate the Payment method as Braintree in my mobile Apps as well as my website. So I have installed this plugin on my website  [WooCommerce PayPal Powered by Braintree Payment Gateway](https://wordpress.org/plugins/woocommerce-gateway-paypal-powered-by-braintree/) By WooCommerce. It's working Awesome on my website but I also want to use it for payment by the REST API.
Can I able to do it with this plugin?

Please help if anyone have an idea about it.

**Comment by Mr-AjayM** [comment]
@claudiosanches @mikejolley Can you please look into this and give the suggestions about it.

**Comment by mikejolley** [comment]
Our REST API does not handle payments. It would have security implications. Your app would need to handle payment instead and create/update an order in WC.
