### ISSUE TITLE
API - Invalid Json with 200 Status code

### ISSUE THREAD

**Issue by itzRamkumar** [woocommerce/wc-api-php#165]
Hi,

In Woocommerce api call to get orders i will get **200** Success Status code but it returns invalid json. Here is my response 

Invalid JSON returned for https://mysite/wc-api/v2/orders?filter%5Blimit%5D=-1&status=Processing&filter%5Bcreated_at_min%5D=2017-12-01&filter%5Bcreated_at_max%5D=2018-01-06&consumer_key=myConsumerKey&consumer_secret=MySecretKey. **200** stdClass Object ( [headers] => Array ( [0] => Accept: application/json [1] => Content-Type: application/json [2] => User-Agent: WooCommerce API Client-PHP/2.0.1 ) [method] => GET [url] => https://mysite/wc-api/v2/orders?filter%5Blimit%5D=-1&status=Processing&filter%5Bcreated_at_min%5D=2017-12-01&filter%5Bcreated_at_max%5D=2018-01-06&consumer_key=myConsumerKey&consumer_secret=MySecretKey[params] => Array ( [filter[limit]] => -1 [status] => Processing [filter[created_at_min]] => 2017-12-01 [filter[created_at_max]] => 2018-01-06 [consumer_key] => MySecretKey[consumer_secret] => MySecretKey) [data] => Array ( [filter[limit]] => -1 [status] => Processing [filter[created_at_min]] => 2017-12-01 [filter[created_at_max]] => 2018-01-06 ) [body] => [duration] => 2.19213 ) stdClass Object ( [body] => ‹ìYmoÛ6þ+„>-`Ëz³-i(Ö-í° m1´ÙŠn.Z¢mÎ’¨‘Tš¶Èß%Ùrâ¸[Ò×Í@TÇ#M>¼{î9é%dÆ¤²â?ÞY<³bÏuüAcLÊº˜3iÅ­•JF5ËªÑæ¸áÐq‡Žwêú±ãÅÞôwð©«ì€ï O*Š*g›•Ühê˜•ÜSÇ‰Í?ôRšê6fUR¤L)^.qn-%+Ó7`ÿî×‡`ÐBÓ÷ãÙc§Õó)²4™ç$ç%K¸f…Jþªi©¹†EÜnTÓsXÄéOP+^Uø«±5mì)•:Ùñì|v­Íf\¥¢.,×o7×.™L¯D†§û!§šHÀ6ZÑ7+u’1My£ï¬Æ1Á«D$¯Ð¯5ÂröÉ2®É	•™Yµ¬ÙÅÀšóÎ½Lh–IÀW\p©tRÒ§>çJ3IÄ‚<ák\:§½ÁŠ-ë·¬xc´DÐO!T-ùN¦`¨]9qaÐ%O¨\3Mžk»7äÁÐcvÆrâ{¸˜AÞzÂò¹¨eÉÈo<%¾c® /÷õôùð¬„Ò©ÈÌF_>}øè%ÎFHesÿðÈ @ &äöŸ´,y¹~ÀÓ\Ô™ [ÆV¢Äé‘çÇQ4±“ÍýGA#–Â ˆpÕJ‹‚É„WCèÙÓÀv£‰í¹a´VàB—|àUˆ·6t6Û¹[Ð”—Z¨Õ7þÂ%‚EÎ‰ë$®Ÿx÷­ Ÿ_³ùšk˜äOmBî®WºÈ$‡¸"K–®Å=’®$ìe6šø¶cûžÙa@]PÉ»yýM>Xgœ½NM%µÄ»^i]©x6š¨”âu*ÆRZ©:g /êÙ¨x3¤©	—Ù×š5f£–Í¶|°%¿0òÛÃ iOšÃ~Üq“ÝMÚïðC%yŠñ×¹ì2=ORH8¤8w›’'æ8ÍÍyÈ¼`lÍJ“ÛRduª DN{]×Íd jÎ±f˜'¢ )!µ‹y}Fó72†ÿçtÎÇKN¯.mC\{Ë¤-/v–ý0ìç^Z-c ß½ <^’LkA~‚˜+•JÞ_êULÆ+>Ò]9©àœsqGƒZ±(ðôP9Ð^™C¸wˆu³ªW="ÁP‚KìJhÂ¹úÄ½ŽOãcä¿KìÝ/]å2õÑéV‡Gˆóþ#w%Êesy¤IC›†ìMÜãÅÓb§átü€•¡Í·Ëe~:tü¡ºQìOâ`ŒÅù*í^“Šà{“‚ƒ|ÔæÃ†Ùa))LÁ£YÁKŒª…³)Z C˜3 Ó3¢$x¿F²˜‰*ikuØ)U5lèyn“ÞôŒj*¯pb I˜½”ÍxË?ÆuœyÙ‚Ñ"ðÆî˜MNàøA-˜;ÉûVÝ&w²ûEqGÞG}s,ØÿÃ‚}±!^×ñö©o#›®Sß^<@6TßàÆnôÑÔwRá’ú>˜únËÆÕwÐîíKß?‹UÙ±WKvë­Ü~ \¼þ/DgŸ­D!ùrE¡ËKTß·‘Ú_GUý>UaºWUO§;j²c†Ãr²£”ªºsÙ Jìç÷ Ê«êS+§(ú¢1r@»ýkUí"÷u"ñ€¬ž‚ºèN ‚äcÉjï:¾Y½¾C¬'«7È4ú¼P=R¾1ä;4žö;àw ‚©;ô¶7;£‡  Otûsëq].o…ÓØÁË¾¦•½5NÐål^ùt½Ô¦UÂ¸U§fRøædê•NÍÉ¦U3âåØ©™—ËÇNíøjõ³êà‹~§ÔÑ¼sè'qA\~²ùN]˜áû:5Ü>Z§vüNr“ï$ßK¡WîCÉdû¡â¥éOñä÷o_9.Ç¦îšO%ÿÿì›1Â EOd’I®ál,Ricãí]Ð5@ÖÌ$&Ç-l,dxüÿp›«Jì†F_ê¸*žµlW%~EE\T¦Ü¤­JW%°Œ¹*a·ÁdÇì…ÀE[Gàð%àæ Ëƒ0VTRª$€‡cä†¢Ò«ñrÀ2›ªÉÜª’çÌ¡0ÿ[þ¾_Î`¦Ø¸Ëó·&ø[µ…là£Š¶¶?Ci±©$OúSÉˆ¦Òs;£ñ;}qÁ]…VtpÔD§‚Cu*	L%1þé +8kèð;‹Je˜÷¹ø]&É¿áF€šÅ#vMÀÞ>›ÂMCŒ1¦iwôFâ‘GÊ5HEgGcœ3h­–õµ¦éùÖÿ\×¿d‹]•,Â^sg>Íô~á.$4ëPDBÖE~ühÖûxH¡9½1²˜˜5¨* Œ&f‹PXÕ‡™Ø³3^óÀýñ‡1Cs2&fê¡¬GÃ•èž`ã‡²þÙI½ÂÄ<Ÿ˜×ðÔw^µaÒÜ_o„«ß¨ª‚”UŽžÅ>ÿÿìœÏNÂ@‡_eï^–•ôÆ¿ƒ1Ñè°Q/šx{g¦Nº•m¡é6#°%0‡í·Óß|±Yák €| Ó&äb˜¡»€Œè*§‚&ºÊI¤ÏOgdLU(#ÓuœUýÝñOä!i{ãbŒg ø×ÁmŸGU+Ù •‘3=M2.™ñzûþMót'ÁŒ÷[|+Ÿh£Æ“ËBN°$Žq×ÖL¿HU³aÑ_#(Í²’#¼1¯wSüêÀó0_L_ž–sþAô N$£&§Y‘íü-ƒ&0ª§ZqÃ’EYŠMÔÎ²2\fR³´™ÜîÆs<ÊÊÊÊª~é¤«-dåÈ@¡ÅÞÒSyÃÙßaÁ*VÆ5ýë'‹Ú,h—È­0‹æ7ÏúâÅsÕ/ÉŠ¨#0Yù>32¢‰o_(ƒ5“õÇêÍ#&"Óe!?ïVŸ~gÐ¡hÜA­âly†VñjÐ3½‘µfd¡=ªœÊ_ç*q±ƒcòð!.„bW6Ùâá Ù=*É²¤-‰dpÍöŽÛÍÃ€OUàa‚>Ù3r¨;QÝ‰{H•GR¡—.ÊÿÿR.Èˆ­ÿÿ|h„|Æ\ [code] => 200 [headers] => Array ( [Date] => Thu, 04 Jan 2018 08:58:07 GMT [Server] => Apache [X-Powered-By] => PHP/5.6.32 [Link] => ; rel="last" [X-WC-Total] => 8 [X-WC-TotalPages] => 0 [Set-Cookie] => jckwds-guest-user-id=jckwds5a4deca065d75; path=/ [Upgrade] => h2 [Connection] => Upgrade [Vary] => Accept-Encoding,User-Agent [Content-Encoding] => gzip [Transfer-Encoding] => chunked [Content-Type] => application/json; charset=UTF-8 ) )

can anyone please look at this?

**Comment by claudiosanches** [comment]
This doesn't sound like an issue with this REST API library.
