### ISSUE TITLE
Errors contain objects not arrays

### ISSUE THREAD

**Issue by uuf6429** [woocommerce/wc-api-php#167]
Since v2.0.0, the API returns objects instead of arrays. In places where the library itself consumes/uses the response, this change has to be reflected.

So far I only found about this here (`message` and `code` should be properties):
https://github.com/woocommerce/wc-api-php/blob/f7342e78f8927c09ae3a2adf7f6cf9c365aa6776/src/WooCommerce/HttpClient/HttpClient.php#L341...L342

**Comment by wheelsailor** [comment]
Thanks. To save others time and so google can find this easier. 
I am running V2.0.0 of this plugin, Wordpress  4.9.4
and on calling $woocommerce->get('orders');

I am getting PHP errors:

( ! ) Fatal error: Uncaught Automattic\WooCommerce\HttpClient\HttpClientException: Syntax error in C:\wamp64\www\wordpress\wp-content\plugins\myplugin\vendor\automattic\woocommerce\src\WooCommerce\HttpClient\HttpClient.php on line 340
--
Warning: rawurldecode() expects parameter 1 to be string, array given in C:\wamp64\www\wordpress\wp-content\plugins\get-entries\vendor\automattic\woocommerce\src\WooCommerce\HttpClient\OAuth.php on line 104
