### ISSUE TITLE
Ionic 3 woocommerce no product display on my app??Any can help please? 

### ISSUE THREAD

**Issue by farhaanabdulla** [woocommerce/wc-api-php#171]
enter code here
Home.ts-
import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';
import * as WC from 'woocommerce-api';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

WooCommerce: any;
 products: any[];

         //   Home=HomePage;

   constructor(public navCtrl: NavController) {

    this.WooCommerce = WC({
      url: 'xxxxxxxxxxxxxx', // Your store URL
      consumerKey: 'xxxxxxxxxxxx', // Your consumer key
      consumerSecret: 'xxxxxxxxxxxxxx', // Your consumer secret
      wpAPI: true, // Enable the WP REST API integration
      queryStringAuth: true,
      verifySsl: true,
      version: 'wc/v2' // WooCommerce WP REST API version
    });

  }
    this.WooCommerce.getAsync("products").then( (data) => {
      console.log(JSON.parse(data.body));
      this.products = JSON.parse(data.body).products;
    }, (err) => {
      console.log(err)
    });

  }
 
}

**Comment by farhaanabdulla** [comment]
> <ion-header>
  <ion-navbar>
    <button ion-button menuToggle>
      <ion-icon name="menu"></ion-icon>
    </button>
    <ion-title>Home</ion-title>
  </ion-navbar>

</ion-header>
<ion-content no-padding>
  <ion-card>
    <ion-slides loop="true" autoplay="3000" pager>
      <ion-slide *ngFor="let number of [1,2,3]">
        <img src="./assets/imgs/{{number}}.jpg" />
      </ion-slide>
      
    </ion-slides>
  </ion-card>
  <img style="margin-top: 10px;" src="./assets/images/banner2.jpg" />

  <ion-grid>
    <ion-row>
      <ion-slides>
        <ion-slide *ngFor="let product of products">
          <ion-card no-padding>
            <img [src]="product.featured_src" />
            <h1> {{ product.title }} </h1>
            <p> {{ product.short_description }}</p>
          </ion-card>
        </ion-slide>
      </ion-slides>
    </ion-row>
  </ion-grid>
  
</ion-content>

**Comment by farhaanabdulla** [comment]
[full.txt](https://github.com/woocommerce/wc-api-php/files/1717730/full.txt)

**Comment by kondasMajid** [comment]
hey. did you find solution to your problem
