### ISSUE TITLE
used lib without composer

### ISSUE THREAD

**Issue by marotn** [woocommerce/wc-api-php#172]
Hi,
How can i used this lib in my projet php without composer?

**Comment by capriciousalex** [comment]
Download composer to your local machine, use the `composer require automattic/woocommerce` command in your command line, then upload the files along with the **vendor** folder to your hosting.

**You can then load the namespace like this:**
```
require __DIR__ . '/vendor/autoload.php';
use Automattic\WooCommerce;
```

Hope that helps!
