### ISSUE TITLE
Invalid signature - provided signature does not match. 

### ISSUE THREAD

**Issue by arcmax1998** [woocommerce/wc-api-php#175]
```
require_once(__DIR__.'/WooCommerce/Client.php');
require_once(__DIR__.'/WooCommerce/HttpClient/BasicAuth.php');
require_once(__DIR__.'/WooCommerce/HttpClient/HttpClient.php');
require_once(__DIR__.'/WooCommerce/HttpClient/HttpClientException.php');
require_once(__DIR__.'/WooCommerce/HttpClient/OAuth.php');
require_once(__DIR__.'/WooCommerce/HttpClient/Options.php');
require_once(__DIR__.'/WooCommerce/HttpClient/Request.php');
require_once(__DIR__.'/WooCommerce/HttpClient/Response.php');
use Automattic\WooCommerce\HttpClient\HttpClientException;

use Automattic\WooCommerce\Client;

// wp-json/wc/v2/
$woocommerce = new Client(
    'http://xxx.com/wooapi/', 
    'ck_xxx9374108418327c64141ecc0f6d0c5abf615d9', 
    'cs_xxxde3a7f2d0c2253dabc492f5f01d2114094461',
    [
        'wp_api' => true,
        'verify_ssl'=>false,
        'query_string_auth' => true,
        'version' => 'v2',
    ]
);
var_dump($woocommerce);
print_r($woocommerce->get('products'));
```
I get this error  - Fatal error: Uncaught exception 'Automattic\WooCommerce\HttpClient\HttpClientException' with message 'Error: Invalid signature - provided signature does not match. [woocommerce_rest_authentication_error]'

However if run the same ck and cs credentials on post man on the http://xxx.com/wooapi/wp-json/wc/v2/products/ it returns the correct json ... what am i doing wrong ?

**Comment by andresnijder** [comment]
+1 
i can reproduce the same results

**Comment by andresnijder** [comment]
@arcmax1998 i tried it with `wp_api' => false` and got a good response

**Comment by callumstrubi** [comment]
Getting exactly the same but with wp_api => false I get a 400 error with body of "-1".

**Comment by callumstrubi** [comment]
After much testing, it would appear that there is nothing wrong with the way the API generates it's signature. Maybe the testing of signatures in WooCommerce is broken?

**Comment by arcmax1998** [comment]
the thing is that the moment i put https everything works... i remove it
and it stops working.... i tried on linux and on wamp ....

thanks
Apurva M

**Comment by callumstrubi** [comment]
Is this abandonware at this stage?

**Comment by claudiosanches** [comment]
Tested and works just great, probably different timezone from your app and server.

**Comment by claudiosanches** [comment]
@callumstrubi is supported, you can send your own `oauth_timestamp`.

**Comment by callumstrubi** [comment]
Sending an oauth_timestamp (which is UTC) appears to not fix the issue.

**Comment by claudiosanches** [comment]
@callumstrubi need to send in the same timezone than the website/server.

**Comment by callumstrubi** [comment]
That's exactly the problem though, a unix timestamp should be in UTC, always. Should i be creating a fake timestamp that is adjusted for the receiving server's timezone? 

time() is coherent to the spec, so time() will always provide a timestamp in UTC, so will rarely work, and probably be why there are so many of these tickets with the oauth signature issue (because those working on localhost or shared environments can't control the time zone, and there are sometimes good justifications for running a production server in local time).

Should there be an internal change to the API such that the timestamp used to check the signature is done in UTC?

**Comment by Ayeshh** [comment]
@callumstrubi Been struggling with the oauth signature issue for a while now... what worked for you?

**Comment by bitsnaps** [comment]
Make sure your're able to connect to your woocommerce rest with postman and with your local ip address:
https://stackoverflow.com/questions/52452498/woocommerce-get-401-when-using-localhost-base-url-but-success-when-using-public/54727413#54727413
I had the same issue.
