### ISSUE TITLE
Filtering /products/ by "attribute" does not work

### ISSUE THREAD

**Issue by stratease** [woocommerce/wc-api-php#177]
Not clear on how to filter results by 'attributes'. It is listed as a parameter in the [REST documentation](https://woocommerce.github.io/woocommerce-rest-api-docs/?php#list-all-products), but I don't see any details on how to specify it in a GET request?

```
use Automattic\WooCommerce\Client as WooClient;

$woocommerce = new WooClient(
    'https://store.mystore.com',
    'key',
    'secret',
    [
        'wp_api' => true,
        'verify_ssl' => false,
        'version' => 'wc/v2',
    ]
);

$r = $woocommerce->get('products', ['attribute' => 'not-working']);
print_r($r); // returns all results

```

**Comment by claudiosanches** [comment]
This question is not related to this REST API wrapper, please for questions about WooCommerce REST API use the support forum: https://wordpress.org/support/plugin/woocommerce
