### ISSUE TITLE
Dont work on on php 7.1

### ISSUE THREAD

**Issue by nikita6631** [woocommerce/wc-api-php#180]
POST /wp-json/wc/v2/products?oauth_consumer_key=ck_2a3c7379ce70b9c7e04a1beef989adf5db052380&oauth_nonce=fda40160cd970c2782b5a69d3d8bfdb56879b8ab&oauth_signature=ebF1IWmoBSGYG%2BODaTAAojXfAL6yFPhQ5nlHuakEK%2BI%3D&oauth_signature_method=HMAC-SHA256&oauth_timestamp=1520873333 HTTP/1.0" 400 274 "-" "WooCommerce API Client-PHP/2.0.0

**Comment by claudiosanches** [comment]
Works just fine with PHP 7.1.
