### ISSUE TITLE
WooCommerce REST API: Create Order Email Invoice no products displayed

### ISSUE THREAD

**Issue by johnjovenbayutas** [woocommerce/wc-api-php#181]
Hi,

Good day to all.

I just want to ask if anyone had experience this issue and made a solution.

I'm having trouble creating order using WooCommerce REST API. The order was successfully posted. However, the email notification or the invoice sent doesn't display the products and the billing information of the customer. In the Wordpress Admin WooCommerce->Orders, all details were posted. The Customer's information and products were displayed.

Any idea on how to solve this? Your reply is greatly appreciated.

Many thanks

**Comment by jasie** [comment]
The emails have nothing to do with this wrapper for the WC REST API (wc api php client), I think...

**Comment by johnjovenbayutas** [comment]
Any ideas where should I start trouble shooting? I perform different test orders and only the orders created via REST API had this issue (that no products and customer's billing and shipping information displayed) in the Email Confirmation Invoice. However, when your try to resend the invoice in the admin section, all information including the products was displayed.
