### ISSUE TITLE
Update Webook Status

### ISSUE THREAD

**Issue by kgatan** [woocommerce/wc-api-php#182]
I'm trying to disable a "product.updated" hook before running a product sync job but cant change the hook status using the api.

All other writable webhook fields work as expected.

```
$woocommerce = new Client(
    'https://url.com',
    'key',
    'secret',
    [
        'wp_api' => true,
        'version' => 'wc/v2',
    ]
);

try{
  $data = [
    'status' => 'disabled'
  ];
  print_r($woocommerce->put('webhooks/5', $data));
}catch (HttpClientException $e) {
    print_r($e);
}
```

Is this a bug or is there somthing I've missed that locks the webhook for status changes?

**Comment by claudiosanches** [comment]
This question is not related to this REST API wrapper, please for questions about WooCommerce REST API use the support forum: https://wordpress.org/support/plugin/woocommerce
