### ISSUE TITLE
Fatal error: Uncaught WC_API_Client_HTTP_Exception: Invalid JSON returned

### ISSUE THREAD

**Issue by alanlaithwaite** [woocommerce/wc-api-php#188]
We can read the product information, we can create a new product, but when we try to update a known product using its ID we get this error Fatal error: Uncaught WC_API_Client_HTTP_Exception: Invalid JSON returned
I have looked at some older issues about similar problems but they do not resolve my issue as I say we seem to be connection, and onlu updates seems effected, we have the latest woo-commerce and wordpress installed.
Many thanks for any help.
Alan

**Comment by claudiosanches** [comment]
> Fatal error: Uncaught WC_API_Client_HTTP_Exception

This means that you should use `try/catch` to catch that exception.

**Comment by alanlaithwaite** [comment]
Hi thank you we are using try/catch this is a test site on local server and the full error reported is below,
thanks Alan

( ! ) Fatal error: Uncaught WC_API_Client_HTTP_Exception: Invalid JSON returned for http://wpv9.techniframe.co.uk/wc-api/v2/products/349?oauth_consumer_key=ck_67a8f7bd13e383440d5b5b5a65b98e75a87ea1d7&oauth_timestamp=1523375980&oauth_nonce=765ecc8cb749a577fd6fb4abe78c2a9c6a92e571&oauth_signature_method=HMAC-SHA256&oauth_signature=%2Fya7GxdiWU5rexDSQYoqDY3yAbL47F5F%2F93g%2BaZ6VTI%3D. in D:\workspace\vs2013\smty_wcapi\lib\woocommerce-api\class-wc-api-client-http-request.php on line 182
--



1 | 0.0250 | 379624 | {main}( ) | ...\example.php:0
2 | 5.1941 | 648688 | WC_API_Client_Resource_Products->update( ) | ...\example.php:124
3 | 5.1942 | 649008 | WC_API_Client_Resource_Products->do_request( ) | ...\class-wc-api-client-resource-products.php:107
4 | 5.1943 | 649048 | WC_API_Client->make_api_call( ) | ...\abstract-wc-api-client-resource.php:122
5 | 5.1973 | 653736 | WC_API_Client_HTTP_Request->dispatch( ) | ...\class-wc-api-client.php:286

**Comment by claudiosanches** [comment]
Does not sounds like you are using `try/catch` if still is throwing a fatal error, or maybe using a different PHP library.

**Comment by alanlaithwaite** [comment]
Hi Claudio
This the result from the catch, the update was not updating the remote data so set the catch to find out what the problem is, the issue seems to be the returned data in not JSON, had the API updated the remote information I would remove the print out of the exception, but needed to know why the information was not being updated. I hope this makes sense.
Thanks.
Alan

**Comment by claudiosanches** [comment]
If the JSON is not returned or valid, sounds more like an issue on your site, some plugin causing errors, than an issue with this REST API library.

**Comment by alanlaithwaite** [comment]
Hi sorry to be a pain, but I have disabled all plugins apart from woo-commerce main plugin and still get the same error using the examples supplied in the woo-commerce API php examples.

( ! ) Fatal error: Uncaught WC_API_Client_HTTP_Exception: Invalid JSON returned for http://wpv9.techniframe.co.uk/wc-api/v2/products/349?oauth_consumer_key=ck_67a8f7bd13e383440d5b5b5a65b98e75a87ea1d7&oauth_timestamp=1523383727&oauth_nonce=10bcbc63538623281da4b461e0c057d8ab7eb169&oauth_signature_method=HMAC-SHA256&oauth_signature=yRSoNTUxkwusNz4PDshymdtQm2%2FIqKHYic5nwjJNnLU%3D. in D:\workspace\vs2013\smty_wcapi\lib\woocommerce-api\class-wc-api-client-http-request.php on line 182
--



1 | 0.0244 | 379624 | {main}( ) | ...\example.php:0
2 | 3.6137 | 648688 | WC_API_Client_Resource_Products->update( ) | ...\example.php:124
3 | 3.6138 | 649008 | WC_API_Client_Resource_Products->do_request( ) | ...\class-wc-api-client-resource-products.php:107
4 | 3.6139 | 649048 | WC_API_Client->make_api_call( ) | ...\abstract-wc-api-client-resource.php:122
5 | 3.6161 | 653672 | WC_API_Client_HTTP_Request->dispatch( ) | ...\class-wc-api-client.php:286

**Comment by claudiosanches** [comment]
@alanlaithwaite I just checked the error message, see that there is no file like `woocommerce-api\class-wc-api-client-http-request.php` in this REST API library.
You can check the files here: https://github.com/woocommerce/wc-api-php

So as I said:

> Does not sounds like you are using try/catch if still is throwing a fatal error, or maybe using a different PHP library.

You are using a different library, I can only help with you are having trouble with this library.

**Comment by alanlaithwaite** [comment]
Thank you I have downloaded from the link you sent and will give it a try tomorrow.
Alan

**Comment by alanlaithwaite** [comment]
Hi, sorry looks like it is a different lib, kloon/WooCommerce-REST-API-Client-Library I will try to contact them, again thanks for your assistance.
Alan
