### ISSUE TITLE
Results shows only 10 Values

### ISSUE THREAD

**Issue by mkh01** [woocommerce/wc-api-php#189]
I'm trying to dump the products results array, it shows me only 10 values even if i tried something else like customers.

**Comment by mkh01** [comment]
$results = $woocommerce->get('products', array('filter[limit]'=>1000));

This worked

**Comment by jhoanborges** [comment]
> $results = $woocommerce->get('products', array('filter[limit]'=>1000));
> 
> This worked

Not working for me
