### ISSUE TITLE
Woocommerce REST APi: Fetching customers with specific username gets all the customers

### ISSUE THREAD

**Issue by ahmedsamyabdelhay** [woocommerce/wc-api-php#192]
Steps to reproduce the issue:

1. conduct a get request to fetch customers
2. add username="value" as a query parameter
3. log the the returned customers

Expected/actual behavior:

When I follow those steps, I see the list of the whole customers returned

I was expecting to see only the list of the customers whose usernames match the passed query value

**Comment by claudiosanches** [comment]
`username` is not a valid query parameter.
Note that this repository is only for the PHP REST API library.
