### ISSUE TITLE
How to set featured image to an external url and not have Wordpress upload to media library?

### ISSUE THREAD

**Issue by wyatt121** [woocommerce/wc-api-php#193]
Hi,

I have the API working, but  Wordpress uploads the image to the media library and sets the uploaded image as the featured image. This is not good for my setup. All my product images stored on a dedicated image server, and I want them served from there. How do I force Wordpress to not upload the image and instead just put my image URL in the featured image field?

Any help is much appreciated.

Wyatt

**Comment by claudiosanches** [comment]
This doesn't sound like a question related to this REST API library.
For questions about the WooCommerce REST API use https://wordpress.org/support/plugin/woocommerce
