### ISSUE TITLE
How to echo response codes?

### ISSUE THREAD

**Issue by wyatt121** [woocommerce/wc-api-php#194]
Hi,

I am able to add a product easily using the code below.  It all works, but I get no feedback printed back to the screen stating everything went ok.  I assume if something fails, errors will be thrown back at me.    I found the response code on this page here, but I'm unsure how to use it.  

https://packagist.org/packages/automattic/woocommerce

Basically, I'm hoping to echo out "hey everything went as planned", or the full json body response, or errors.  I'm having trouble finding any tutorials on how to handle this Woocommerce response code.  Do you have a tutorial, or can you point me in the right direction?  Any help is much appreciated.

`
use Automattic\WooCommerce\Client;

$woocommerce = new Client(
	'https://www.hometownapparel.com',
	'blah',
	'blah',
	[
		'wp_api'  => true,
		'version' => 'wc/v2',
	]
);

$prod_data = [
	'name'          => 'A NICE product',
	'type'          => 'simple',
	'regular_price' => '15.00',
	'description'   => 'A very meaningful product description',
	'images'        => [
		[
			'src'      => 'http://img2.hometownapparel.com/images/TS-P002-M-GR-D001-LT002-BL.jpg',
			'position' => 0,
		],
	],
	'categories'    => [
		[
			'id' => 999,
		],
	],
];

$woocommerce->post( 'products', $prod_data );
`

**Comment by claudiosanches** [comment]
There's an example already in the README.md: 

https://github.com/woocommerce/wc-api-php/blob/master/README.md#response
