### ISSUE TITLE
Filtering products using attributes does not work

### ISSUE THREAD

**Issue by ahmedsamyabdelhay** [woocommerce/wc-api-php#195]
I have an attribute called "Flavor" with ID: 1 and an attribute_term within the flavor attribute called "Banana" with ID:23 ... when I try to retrieve products with Banana Flavor using the following query:

this.WooCommerce.getAsync("products/?attribute=1&attribute_term=23&page=1").then( async (data) => { let newProducts = JSON.parse(data.body); console.log(newProducts) }, (err) => { console.log(err) });

I get the entire list of existing products.

**Comment by ahmedsamyabdelhay** [comment]
@akshaypitale This is how I did it:

For attribute name: Flavor and attribute term id of "23"
getAsync("products/?attribute=pa_flavor&attribute_term=23&page=1")

**Comment by claudiosanches** [comment]
This doesn't sound like a question related to this REST API library.
For questions about the WooCommerce REST API use https://wordpress.org/support/plugin/woocommerce
