### ISSUE TITLE
product does not create

### ISSUE THREAD

**Issue by mohammadlom** [woocommerce/wc-api-php#196]
I have installed this library in laravel 4 and I used it.I have faced no issue till I want to upload image from my server.I set image urls correctly but when I call wrapper function for creating product I have faced an error that told me I'm wrong in my images url.
can anyone help me in product data array with images
my data array:
`['product'  => [
                'title'             =>  $product->name,
                'type'              =>  'simple',
                'description'       =>  $product->content,
                'short_description' =>  $product->short_description,
                'regular_price'     =>  $product->regular_price,
                'sale_price'        =>  $product->sale_price,
                'manage_stock'      =>  true,
                'stock_quantity'    =>  $product->stock_quantity,
                'categories'        =>  [['id' => $product->category]],
                'images'            =>  $wooImg
            ]]`

my $wooImg array var_dump() looks like this:
`array(2) { [0]=> array(2) { ["src"]=> string(59) "http://example.com/images/products/01.jpg" ["position"]=> int(0) } [1]=> array(2) { ["src"]=> string(59) "http://example.com/images/products/02.jpg" ["position"]=> int(1) } }`

Is my data array right?

**Comment by claudiosanches** [comment]
Your data looks fine, but need to check if your server can access your images URLs, maybe a proxy or something like that is stopping WordPress to fetch those images, closing since is not a problem on this library.
