### ISSUE TITLE
JSON Response or stdClass Object?

### ISSUE THREAD

**Issue by tmblog** [woocommerce/wc-api-php#197]
Forgive me if I've missed something very obvious however, my response from this for e.g.

`$woocommerce->get('orders', array('status' => 'processing'));`
`print_r($woocommerce);`

Is an 
`Array ( [0] => stdClass Object`
Is this correct? I can see in the documentation for PHP example it is a JSON response without the object, I have simulated with Postman I also get a JSON response like the docs, so why do i get a stdClass Object from my php application? Is there a way to force a JSON response?

I have php version 7.2 installed and the latest versions of Woocommerce and WP.

Any help would be much appreciated.

**Comment by djeraseit** [comment]
Please see release history on first page of this site.

Release History
2018-03-29 - 2.0.1 - Fixed fatal errors on lookForErrors.
**2018-01-12 - 2.0.0 - Responses changes from arrays to stdClass objects. Added follow_redirects option.**

**Comment by vikingmaster** [comment]
This is the change: https://github.com/woocommerce/wc-api-php/commit/0622cfe36ad77399d66a8d3cf45ce4381fcf87a1#diff-ee41581ecc10cc4c057d42638d36badfL345

What made you change array-typed response to StdClass, guys? :)

Instead, there could be an option to choose the type response objects, defaulting to array. And also all woocommerce responses are built using arrays like here:
https://github.com/woocommerce/woocommerce/blob/master/includes/api/v1/class-wc-rest-order-refunds-controller.php#L123

Would you consider adding a flag to configuration?
