### ISSUE TITLE
Invalid JSON returned, but the JSON gets lost

### ISSUE THREAD

**Issue by javorszky** [woocommerce/wc-api-php#198]
Occasionally when batch updating orders, we run into an invalid json returned error.

It's being thrown here: https://github.com/woocommerce/wc-api-php/blob/master/src/WooCommerce/HttpClient/HttpClient.php#L374

What's the best way to log the body of the response that failed JSON parsing? That way we could figure out where the problem is.

**Comment by claudiosanches** [comment]
In the `HttpClientException` object there is already the `response` and `request` objects.

```php
} catch ( $e HttpClientException ) {
    print_r( $e->getResponse()->getBody() ); // Raw response body
}
```
