### ISSUE TITLE
Get Category Name on Orders request?

### ISSUE THREAD

**Issue by tmblog** [woocommerce/wc-api-php#199]
Using the Orders request is there a way to get the category names for the line_items?

Currently it returns all line items and their names, prices etc but not category name that it belongs to, would love to group them by category to print it out for a picking list. At the moment the order is received in the order the items were placed in the cart.

Original order:

1. red T-shirt
1. blue shorts
1. orange t-shirt

Then group it so it looks like this:

1. red T-shirt
1. orange t-shirt
1. blue shorts

Is this possible? If not what would be a good way to do it?

**Comment by claudiosanches** [comment]
This doesn't sound like a question related to this REST API library.
For questions about the WooCommerce REST API use https://wordpress.org/support/plugin/woocommerce
