### ISSUE TITLE
fetch multiple products by id(s)

### ISSUE THREAD

**Issue by andpetros** [woocommerce/wc-api-php#200]
Hi,

We are trying to fetch several products based on their id(s) and we are using the 'include' parameter for this.
Below is the code:

$includeEncoded = urlencode('include[]');
$woocommerce->get('products',array($includeEncoded=>array(3247,3249)));

This is returning only the last item (3249).

What we need is the return of all specified products (in this case 3247, 3249, etc.).

Would appreciate your input in resolving this issue. 

Thanks

**Comment by claudiosanches** [comment]
No need to send as an array, you can send as a comma separated list.
