### ISSUE TITLE
PHP curl timeout to post product by api

### ISSUE THREAD

**Issue by faberpp** [woocommerce/wc-api-php#201]
Hello,
I have a timeout when i post product with a long text description in API, but when i make the same post using then postman its works.
Anybody with the same problem?
Thanks.

**Comment by ipullrank** [comment]
I'm having a very similar issue. Where the batch request times out, but when I put it on Postman it works fine. 

I'm posting WooCommerce IDs and stock statuses. I have a nearly identical function in another script  that I wrote that just posted WC IDs and weights and it worked fine.

Did you figure it out?

**Comment by claudiosanches** [comment]
Just set up a long `timeout`: https://github.com/woocommerce/wc-api-php#client-options
By default is 15 seconds.
