### ISSUE TITLE
Get orders with multiple statuses?

### ISSUE THREAD

**Issue by tmblog** [woocommerce/wc-api-php#204]
Is it still possible to get orders with multiple statuses using api v2?

`$shop->get('orders', array('status' => 'completed,processing'));`

I am getting an error? Was able to previously but not able to anymore. Any chance of including this again soon? Cheers.

**Comment by HuberStefan** [comment]
I have the same problem, with the old api version it was possible to get orders with multiple statuses, but now the filter is not working.

**Comment by claudiosanches** [comment]
Not support in v2, but implemented into v3.
