### ISSUE TITLE
missing vendor/autoload.php

### ISSUE THREAD

**Issue by shafinraza** [woocommerce/wc-api-php#206]
Dear Team,
Please guide me i don't have vendor/autoload.php file in woo commerce Plugin.

**Comment by shafinraza** [comment]
Dear Team i m getting error in example.php
![image](https://user-images.githubusercontent.com/17063064/41083623-3e28887c-6a4f-11e8-9e28-b7a4d432a5ea.png)
Please check and revert.
Thanks.

**Comment by manojhl** [comment]
@shafinraza `vendor/autoload.php` is added when you run `composer install` in your temminal. It will autoload woocommerce classes when required.

**Comment by claudiosanches** [comment]
Just follow the README.md, there is all steps there already.
This autoload.php comes from composer, you need to install first.

**Comment by Uriel1339** [comment]
Hey just in case you are not able to use Composer or figure it out. Here is the PHP Library that you can download separately, no tools or registration required:
https://php-download.com/package/automattic/woocommerce

I hope this helps and gets added to the official README.md.

Good luck out there!

Sincerely,

[Andreas Lopez](https://www.linkedin.com/in/andreaslopez/) aka [@Uriel1339](https://twitter.com/Uriel1339)

**Comment by claudiosanches** [comment]
@Uriel1339 sorry, but probably better to prefer a modern solution as composer, this is a standard for almost every PHP project, at least for unit tests and more... That's why is already registered as a composer library.
