### ISSUE TITLE
Fatal errors:  Uncaught exceptions 'Automattic\WooCommerce\HttpClient\HttpClientException' 

### ISSUE THREAD

**Issue by 21stcn** [woocommerce/wc-api-php#207]
I am sure this is not really the place for this question but I don't really know where to ask.

I am failing to understand how to handle errors gracefully with this client.

As a small example, I have a function to get user downloads:

```
function get_user_downloads($user_id){
	
	if($downloads = $woocommerce->get('customers/'.$user_id.'/downloads')){
		return $downloads;
	}
	return false;
}
```

So now if I run this function anywhere and if, for example, the user id does not exist, I would want the function to return false (or access the error message), but for my application to keep running. 

Instead, I get the following:
`
Fatal error: Uncaught exception 'Automattic\WooCommerce\HttpClient\HttpClientException' with message 'Error: Resource does not exist. [woocommerce_rest_customer_invalid]' in .../vendor/wc-api-php/WooCommerce/HttpClient/HttpClient.php:348 Stack trace: #0 .../vendor/wc-api-php/WooCommerce/HttpClient/HttpClient.php(378): Automattic\WooCommerce\HttpClient\HttpClient->lookForErrors(Object(stdClass)) #1 ...vendor/wc-api-php/WooCommerce/HttpClient/HttpClient.php(414): Automattic\WooCommerce\HttpClient\HttpClient->processResponse() #2 .../vendor/wc-api-php/WooCommerce/Client.php(82): Automattic\WooCommerce\HttpClient\HttpClient->request('customers/2685 in .../vendor/wc-api-php/WooCommerce/HttpClient/HttpClient.php on line 348 `

So my application breaks. But there is a clear error message:  

> **"Error: Resource does not exist"**
> [woocommerce_rest_customer_invalid]'

How can I receive this error message without a fatal error? How can I test for a route without my app breaking? Could someone help me understanding what I am doing incorrectly. I can't find anything useful in the readme.

Sorry for the noob question here.

**Comment by xewl** [comment]
As the error itself states, you're not catching the `HttpClientException`.
You need to `try { ... } catch(HttpClientException $e) { $err = $e->getMessage(); }`.
