### ISSUE TITLE
Product & variation deleting doesn't remove attachments and image files

### ISSUE THREAD

**Issue by virulaine** [woocommerce/wc-api-php#210]
Hi,

When I delete product or variation via API, there are still attachments in the database and image files on the disk. This is critical bug because while importing/deleting about 100 products with 30 variations each could end up with 14000 image files left and insufficient disk space.
I have to create hooks for Wordpress to clean it all up:

    add_action( 'woocommerce_rest_delete_product_object', 'delete_product', 10, 1);
    function delete_product($product) {
        // Delete main product image
        wp_delete_attachment($product->get_image_id(), true);

        $attachment_ids = $product->get_gallery_image_ids();

       // Delete all related product images
       foreach( $attachment_ids as $attachment_id ) {
           wp_delete_attachment($attachment_id, true);
       }	
    }

    add_action( 'woocommerce_rest_delete_product_variation_object', 'delete_product_variation', 10, 1);
    function delete_product_variation($product) {
        wp_delete_attachment($variation->get_image_id(), true);
    }

**Comment by vagovszky** [comment]
I'm voting for this feature.

**Comment by claudiosanches** [comment]
This doesn't sound like a question related to this REST API library.
For questions about the WooCommerce REST API use https://wordpress.org/support/plugin/woocommerce
