### ISSUE TITLE
Wocommerce API request - error 401

### ISSUE THREAD

**Issue by swietnegranie** [woocommerce/wc-api-php#223]
I use bundle Automattic\WooCommerce to connect with my woocommerce shop api and now I have an error 401 'Sorry, but you can not view this resource.' when I send request GET to my shop api.

This connection to api works fine until I move my shop to another server. What could be the reason for the error?

Perhaps this is due to blocking the port on the server after which requests to the api are received. What is the port for api in woocommerce?

Thanks for every help.

**Comment by claudiosanches** [comment]
> This connection to api works fine until I move my shop to another server. What could be the reason for the error?

This doesn't sound like a question related to this REST API library.
For questions about the WooCommerce REST API use https://wordpress.org/support/plugin/woocommerce
