### ISSUE TITLE
query_string_auth

### ISSUE THREAD

**Issue by swietnegranie** [woocommerce/wc-api-php#224]
I want to ask, if I force Basic Authentication as query string (using in options: query_string_auth: true), then I send request with open available consumer_key and consumer_secret in  url address? So if I use it in my application, everyone see this parameters? Wheter parameters are send in secret and consumer_secret is encrypted?

Thanks for every help and tips.

**Comment by claudiosanches** [comment]
The most security way is to enable on your server support for authentication headers, so you don't need to for this as a query string, so yes, it's not too security if you pass into the URL, but in some servers this is the only way to go.
