### ISSUE TITLE
Unexpected 'rest_no_route' when creating Brand

### ISSUE THREAD

**Issue by yulumadavid** [woocommerce/wc-api-php#229]
Since the update to 3.5.1 we get this error from the REST API when creating a Brand.

Additional information:
url = products/brands
methode = post
parameters ->
{
“name”: “Helen B.”
}
response ->
“{\”code\”:\”rest_no_route\”,\”message\”:\”Geen route gevonden die overeenkomt met de URL en aanvraagmethode\”,\”data\”:{\”status\”:404}}”

**Comment by stuartduff** [comment]
Hi David,

Testing using [Postman](https://www.getpostman.com/) I was able to retreive and insert data for brands via the API in WooCommerce v3.5.1 from this path below when using the WooCommerce Brands extension.

`wp-json/wc/v3/products/brands`

![kpnhtf](https://user-images.githubusercontent.com/1190565/48270662-7b201d00-e432-11e8-8bcd-880f5b3be231.png)

**Comment by yulumadavid** [comment]
Hi Stuart,

We've managed to solved this one by checking the new Woo API. 

Is there a simple and save way to see if a WooCommerce update contains an API update? I did see some things were changed in the API but did not expect the whole version to change. Or is this how it works?

Thanx for your reply.

**Comment by twf-nikhila** [comment]
@yulumadavid getting the same error, how did you managed to solve it?

**Comment by yulumadavid** [comment]
@twf-nikhila we've updated the WOO API to v3

**Comment by moatazfouad** [comment]
Is there is any updates about this, I still face same issue

**Comment by yulumadavid** [comment]
Today we had this again. Fixed it by resaving the permalinks, after that the endpoint worked again. This is the 5th time since this topic started that we needed to save permalinks to make the endpoint /products/brands work again.
