### ISSUE TITLE
 Error Attempting to Import Product Variations

### ISSUE THREAD

**Issue by evcoin** [woocommerce/wc-api-php#230]
I have been having issues with variable item options. According to
http://woocommerce.github.io/woocommerce-rest-api-docs/#create-a-product
this is the format of adding a product variation.
'options' => [
'S',
'M'
]

Here is my code
'options' => [
$spread_array[$i],
'none'
]
And my output shows
[2] => Array
(
[id] => 3
[position] => 2
[visible] => 1
[variation] => 1
[options] => Array
(
[0] => -101
[1] => none
)

            )

However I keep getting the error below.
Fatal error: Uncaught Automattic\WooCommerce\HttpClient\HttpClientException: Error: Invalid parameter(s): attributes [rest_invalid_param] in C:\xampp\htdocs\vendor\automattic\woocommerce\src\WooCommerce\HttpClient\HttpClient.php:348 Stack trace: #0 C:\xampp\htdocs\vendor\automattic\woocommerce\src\WooCommerce\HttpClient\HttpClient.php(378): Automattic\WooCommerce\HttpClient\HttpClient->lookForErrors(Object(stdClass)) #1 C:\xampp\htdocs\vendor\automattic\woocommerce\src\WooCommerce\HttpClient\HttpClient.php(414): Automattic\WooCommerce\HttpClient\HttpClient->processResponse() #2 C:\xampp\htdocs\vendor\automattic\woocommerce\src\WooCommerce\Client.php(56): Automattic\WooCommerce\HttpClient\HttpClient->request('products', 'POST', Array) #3 C:\xampp\htdocs\odds.php(372): Automattic\WooCommerce\Client->post('products', Array) #4 {main} thrown in C:\xampp\htdocs\vendor\automattic\woocommerce\src\WooCommerce\HttpClient\HttpClient.php on line 348

**Comment by claudiosanches** [comment]
Have you read the error message?

> Error: Invalid parameter(s): attributes [rest_invalid_param]

That is the response for WooCommerce REST API.
You are not sending the parameters as you suppose to send, maybe reading doc for a version different of the REST API or you are missing something.

Closing since is not an issue with this library.
