### ISSUE TITLE
Orders of bundles do not include a SKU or ID of the child products

### ISSUE THREAD

**Issue by joeyc002** [woocommerce/wc-api-php#232]
When retrieving an order for a bundled product, there is no key that indicates that it is a bundled product and the "meta_data" key lists only the product name and not the ID or SKU of the product. 

For example, the order below is for a bundle of 6 individual items. The only indicator would be the product name which isn't ideal to use to link to the actual product as it is possible to create duplicate products with the same name. There is a bundle product ID for the individual product but this can be changed AFTER the order has been placed and so would affect the order.

I'd suggest adding a SKU for the bundled products or an ID to the actual product, the quantity as an integer and also a top level key which will indicate whether or not the product is a bundle. 

```
"line_items": [
      {
        "id": 123,
        "name": "Mix And Match",
        "product_id": 1234,
        "variation_id": 0,
        "quantity": 1,
        "tax_class": "",
        "subtotal": "48.00",
        "subtotal_tax": "0.00",
        "total": "48.00",
        "total_tax": "0.00",
        "taxes": [],
        "meta_data": [
          {
            "id": 3880,
            "key": "_wcsatt_scheme",
            "value": "0"
          },
          {
            "id": 3881,
            "key": "PRODUCT 1",
            "value": "( 2 ) Pouche"
          },
          {
            "id": 3882,
            "key": "PRODUCT 2",
            "value": "( 1 ) Pouche"
          },
          {
            "id": 3883,
            "key": "PRODUCT 3",
            "value": "( 2 ) Pouche"
          },
          {
            "id": 3884,
            "key": "PRODUCT 4",
            "value": "( 1 ) Pouche"
          }
        ]
```

**Comment by claudiosanches** [comment]
This doesn't sound like a question related to this REST API library.
For questions about the WooCommerce REST API use https://wordpress.org/support/plugin/woocommerce
