### ISSUE TITLE
Last totals object's customer count is always zero

### ISSUE THREAD

**Issue by SuryaJD** [woocommerce/wc-api-php#235]
I am using Woocommerce Api in my local Crm application.
And calling Sales report data.
`$query = [
'context'  => 'view',
'date_min' => '2019-01-01', 
'date_max' => '2019-01-22'
];
$sales_report = $woocommerce->get('reports/sales', $query);`

But when I get $sales_report object, I came to know that customer count from last date (in this case [2019-01-22] object ) from [totals] object is always zero. If I alter date_max to '2019-01-10' than Customer count Of 10th of jan will show as Zero.
Full Code pasted On pastebin >> [https://pastebin.com/UdTSfSnq](https://pastebin.com/UdTSfSnq)  
Full Output Is as follow >> [https://pastebin.com/nbecistE](https://pastebin.com/nbecistE)
If I change 'date_max' from 22nd to 23rd than Customer Count Of 22 would be 8 But 22nd's will be 0
Image link [as 23 as date_max](https://imgur.com/jLa2MLU)
Image Link [as 22 as date_max](https://imgur.com/IERcfj5)

**Comment by claudiosanches** [comment]
Hi there. GitHub is primarily for reporting bugs this REST API library and is not a support forum for WooCommerce REST API. If you have questions about the WooCommerce REST API you should ask on the community support forum here: https://wordpress.org/support/plugin/woocommerce
