### ISSUE TITLE
cURL Error: Could not resolve: catalogue3.test (Domain name not found)

### ISSUE THREAD

**Issue by xoco70** [woocommerce/wc-api-php#236]
Hi, 

I am trying to connect a local WP instance on https://catalogue3.test

With my browser, I can access it with no problem, and browser Woocommerce products

But when I try to access it via PHP ( Laravel ),  with the code:

```
$woocommerce = new Client(
            env('CATALOGUE_URL'),
            'ck_xxx,
            'cs_xxx,
            [
                'wp_api' => true,
                'version' => 'wc/v3',
            ]
        );

        $product = $woocommerce->get('products/27266');
        dd($product);
```

I get:

`cURL Error: Could not resolve: catalogue3.test (Domain name not found)`

What should I do ? I already try in console to make a manual curl on catalogue3.test and it works

**Comment by xoco70** [comment]
I tried to regenerate keys, but I still cant make it work

**Comment by xoco70** [comment]
I'm doing it only with curl, and still the same error, so it is not coming from the plugin. closing !

**Comment by tillkruss** [comment]
What was the issue?
