### ISSUE TITLE
Question: is there a way to change the shipping class of a specific product trough the API?

### ISSUE THREAD

**Issue by yulumadavid** [woocommerce/wc-api-php#237]
I see shipping classes are available in the API https://woocommerce.github.io/woocommerce-rest-api-docs/#product-shipping-classes but is there also a way to set a class to a specific product? I can't find any thing calle shipping class in the product object.

**Comment by frinctana** [comment]
Hi, in my product data I have to set shipping_class and shipping_class_id and for me it´s working fine. If I only set the shipping_class_id it´s not working.

$product = [
    'sku' => $sku,
    'name' => $name,
     ...
    'shipping_class' => $shippingClass['name'],
    'shipping_class_id' => $shippingClass['id']
];
Woocommerce::post($endPoint, $product);

**Comment by yulumadavid** [comment]
hi @frinctana thanx for your answer, will check this out!
