### ISSUE TITLE
I can not connect to the api from Angular or postman

### ISSUE THREAD

**Issue by miguelsanz72** [woocommerce/wc-api-php#242]
hello, I'm trying to connect to the api of woocommerce to make an application in angular 8 but I have not found a way to do it, I have already generated the keys and enabled the inherited api in the woocommerce options, but I can not

http://prntscr.com/o03rig

http://prntscr.com/o03sj4

http://prntscr.com/o03taq

I found a way to enable the final routes of the woocommerse api but I do not know where to run that code or in what file to place it

`<?php

include 'vendor/automattic/woocommerce/src/WooCommerce/Client.php';

class Custom_Endpoints_Woocommerce_API
	{
		protected function get_client() {
			return new Client(
				get_site_url(),
				'ck_Xxxxxxxxxxxxxx',
				'cs_xxxxxxxxxxxxxxx',
				[
					'wp_api' => true,
					'version' => 'wc/v3',
				]
			);
		}
		public function register_woocommerce_routes() {
			register_rest_route( 'customroutes', '/products', array(
				'methods' => 'GET',
				'callback' => array( $this, 'view_products' )
			));
		}
		public function view_products( WP_REST_Request $request ) {
			$woocommerce = $this->get_client();
			return $woocommerce->get( 'products/categories' );
		}
	}
`

I can not think of anything else, I hope you can help me

**Comment by claudiosanches** [comment]
Hi there. GitHub is primarily for reporting bugs and is not a support forum. We don’t support custom development here.

Also your code seems like you are trying to do request into your own server, to generate a response for another REST API endpoint, this sounds hacky, probably better to use the REST API controller classes in WooCommerce to build a custom response for your endpoint.
