### ISSUE TITLE
Change Cart Api (Help Needed)

### ISSUE THREAD

**Issue by wifirevaithi** [woocommerce/wc-api-php#243]
Hi,
  Anyone Help me to customize api where i can find function "wp-json/wc/v2/cart/"

**Comment by seb86** [comment]
@wifirevaithi It would be better to [contact me](https://cocart.xyz/feedback/) for information about it since I created the Cart API not WooCommerce.

**Comment by wifirevaithi** [comment]
Bro Already Created The App With That API Now Have a Small Problem So I Need To Just Check It Out.

**Comment by claudiosanches** [comment]
You don't really need a cart API, since there's an `orders` endpoint where you can include products and keep on-hold until you process a payment.
