### ISSUE TITLE
Legacy API

### ISSUE THREAD

**Issue by szepeviktor** [woocommerce/wc-api-php#245]
Docs says https://docs.woocommerce.com/document/woocommerce-rest-api/ I should enable Legacy API.
Using WC 3.6

Could you please elaborate on this? Could it be that this package is legacy?

**Comment by claudiosanches** [comment]
In fact you don't need to enable the legacy REST API, since there's already the WP REST API integration enabled by default, since it's a WordPress default as well.
I'll update this docs. Thanks.

**Comment by claudiosanches** [comment]
You also may want to check the REST API documentation: https://woocommerce.github.io/woocommerce-rest-api-docs/

**Comment by szepeviktor** [comment]
Thank you.

I was confused.

**Comment by flowl** [comment]
@claudiosanches The docs still feel not accurate.

Is the API using the `/wc/` endpoint still developed?

The docs say it's legacy, and the sentence "Prior to 2.6, WooCommerce has had a REST API..." says, there is no more legacy in WooCommerce > 2.6 at all.
This is not true I think, there is still the legacy API in WooCommerce 3.0 if I'm not totally mistaken.

Also it is not clear wether "legacy" means "deprecated"?
