### ISSUE TITLE
Cannot pass multiple parameters as string or array to orders endpoint

### ISSUE THREAD

**Issue by ARH-Digital** [woocommerce/wc-api-php#250]
Not sure if this is an issue, or just lack of documentation. I am attempting to get orders that meet a set of statuses, I cannot get this to work.

Attempting 
`$connection->woocommerce->get('orders', ['status' => 'completed,processing']);` Results in the Fails with
`Automattic/WooCommerce/HttpClient/HttpClientException with message 'Error: Invalid parameter(s): status [rest_invalid_param]'`

Attempting
`$woocommerce->get('orders', ['status' => ['completed', 'processing']]);`
Fails with the same error
`Automattic/WooCommerce/HttpClient/HttpClientException with message 'Error: Invalid parameter(s): status [rest_invalid_param]'`

Passing through a single status works as expected
`$connection->woocommerce->get('orders', ['status' => 'completed']);` 

Passing both options as a sting as per my first example works on the normal wordpress endpoint though
`www.wordpressurl.com/wp-json/wc/v3/orders?status=processing,completed`

Is this achievable?

**Comment by ARH-Digital** [comment]
I noted this on the wrong repsoitory.

**Comment by ARH-Digital** [comment]
Wait, no i didn't. The repository name confused me as, sorry.

**Comment by claudiosanches** [comment]
Hi @ARH-Digital,

Thank you for submitting the issue. However, I can’t reproduce the issue you reported using the steps you provided. Everything is working as expected on my end.

I'm testing with, and all results return as expected.

```php
$woocommerce->get('orders', [
    'status' => [
        'completed',
        'processing'
    ]
]);
```

You haven't shared how you setup this library, but if you are using the `wc/v3` it will works as expected.

```php
$woocommerce = new Client(
    'http://woo.local/',
    'ck_xxxxxx',
    'cs_xxxxxx',
    [
        'version' => 'wc/v3',
    ]
);
```

I hope it helps.
