### ISSUE TITLE
error in PHPDoc

### ISSUE THREAD

**Issue by jszczypk** [woocommerce/wc-api-php#252]
Hi,
Client->get is documented to return an array, while calls to WooCommerce REST API may return an object. 
For example: https://woocommerce.github.io/woocommerce-rest-api-docs/#retrieve-a-product-category
It goes down to HttpClient->parseResponse calling json_decode.

This error in documentation causes error while checking code with tools like PHAN.

Kind regards,
Janusz

**Comment by adameier** [comment]
yep, either PHPdoc should be fixed to reflect the acctual return type, or `json_decode` should be called with the `$assoc` arg set as `true`

**Comment by abishekrsrikaanth** [comment]
There is a PR to fix this https://github.com/woocommerce/wc-api-php/pull/286
