### ISSUE TITLE
JSON ERROR: Syntax error

### ISSUE THREAD

**Issue by alkarana2** [woocommerce/wc-api-php#253]
Hello, your software worked fine. Suddently we get this error and we cant solve it. 
Can you help us please?

Woocomerce version  3.8.1
WooCommerce REST API package: 1.0.2

$woocommerce = new Client($store_url,$eshop_api,$eshop_api2,
    [
        'wp_api' => true,
        'version' => 'wc/v3',
		'query_string_auth' => true,
		'timeout' => 50000
    ]
      try { $woocommerce->get('products/80788'); }
	  catch(Exception $e)
	  { 
	    echo $e->getMessage(); 					  
	  }

We get this ERROR in every call:

JSON ERROR: Syntax error

Fatal error:  Uncaught exception 'Automattic\WooCommerce\HttpClient\HttpClientException' with message 'JSON ERROR: Syntax error' in /var/www/html/CRM/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php:378
Stack trace:
#0 /var/www/html/CRM/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php(422): Automattic\WooCommerce\HttpClient\HttpClient->processResponse()
#1 /var/www/html/CRM/vendor/automattic/woocommerce/src/WooCommerce/Client.php(82): Automattic\WooCommerce\HttpClient\HttpClient->request('products/80788', 'GET', Array, Array)
#2 /var/www/html/CRM/woocommerce_functions.php(66): Automattic\WooCommerce\Client->get('products/80788')
#3 /var/www/html/CRM/pelates.php(2087): include('/var/www/html/C...')
#4 {main}
  thrown in /var/www/html/CRM/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php on line 378

**Comment by tvplinux** [comment]
I have same issue, did you solved?

**Comment by JosChavz** [comment]
Same...
