### ISSUE TITLE
Getting Shipment Tracking number via WC API

### ISSUE THREAD

**Issue by phillipcornwell** [woocommerce/wc-api-php#255]
A user is getting an error when trying to grab the Shipment Tracking number from order details with the following code:

```
$tracking = $woocommerce->get('orders/<order-id>/shipment-trackings');
print_r($tracking);
```

They have the [Shipment Tracking](https://woocommerce.com/products/shipment-tracking/?aff=10486&cid=1131038) extension installed and pointed to the following:

**https://docs.woocommerce.com/document/shipment-tracking/#section-8**

> Works with WooCommerce API v1, v2, and v3 (just added).

Can you share any information on why they cannot pull the tracking number from orders and how to correct it?

Thanks,

**Comment by phillipcornwell** [comment]
FYI: The error they receive is:

```
Error: No route was found matching the URL and request method [rest_no_route] in <site url>
```

**Comment by seuaCoder** [comment]
try api v2 

'version' => 'wc/v2',

**Comment by claudiosanches** [comment]
Hello @phillipcornwell,

This library is just a wrapper, all endpoints on WooCommerce suppose to work, maybe you need to set another version to match the same endpoint of the extension like seuaCoder suggested.

I'm closing for now since it doesn't sounds like an issue on this library.
