### ISSUE TITLE
Is there a way to retrieve Orders before/after modification date?

### ISSUE THREAD

**Issue by alariva** [woocommerce/wc-api-php#289]
Hello!

I see it's possible to list all orders with options `before` and `after` which are applied to the published date (I understand this is the `date_created` field)

https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-orders

Is there a way to filter on the same criteria but using the `date_modified` or also other fields like `date_paid`?

Thanks!

**Comment by JanisE** [comment]
This would probably go as a suggestion to the REST API as such (not its client implementation in PHP). Here https://github.com/woocommerce/woocommerce ?

**Comment by alariva** [comment]
Thanks for pointing out @JanisE , I will take care of rerouting the issue as you suggested.

**Comment by alariva** [comment]
Solved server-side by installing extending functionality with plugin (i.e. https://es.wordpress.org/plugins/products-and-orders-last-modified-for-wc-rest-api/)
