### ISSUE TITLE
HttpClientException: JSON ERROR: Syntax error

### ISSUE THREAD

**Issue by ashwin-kain** [woocommerce/wc-api-php#293]
Getting below error for "automattic/woocommerce": "^3.0".

`Fatal error: Uncaught Automattic\WooCommerce\HttpClient\HttpClientException: JSON ERROR: Syntax error in C:\xampp\htdocs\company\vendor\automattic\woocommerce\src\WooCommerce\HttpClient\HttpClient.php:378 Stack trace: #0 C:\xampp\htdocs\company\vendor\automattic\woocommerce\src\WooCommerce\HttpClient\HttpClient.php(422): Automattic\WooCommerce\HttpClient\HttpClient->processResponse() #1 C:\xampp\htdocs\company\vendor\automattic\woocommerce\src\WooCommerce\Client.php(82): Automattic\WooCommerce\HttpClient\HttpClient->request('products', 'GET', Array, Array) #2 C:\xampp\htdocs\company\cart.php(34): Automattic\WooCommerce\Client->get('products', Array) #3 {main} thrown in C:\xampp\htdocs\company\vendor\automattic\woocommerce\src\WooCommerce\HttpClient\HttpClient.php on line 378`

**Comment by shakethatweight-simon** [comment]
@ashwin-kain  Are you setting the correct url? I just copy and pasted the sample code and also had this error, but it was because I hadn't updated the url

```
$woocommerce = new Client(
    'http://example.com',  // <-- Make sure this is set to the correct url for your site.
```

**Comment by ashwin-kain** [comment]
@shakethatweight-simon Thanks. Resolved.

**Comment by shwetahub** [comment]
'http://localhost/wc-api-php-trunk/' is this wrong url ?
