### ISSUE TITLE
JSON ERROR: Syntax error 

### ISSUE THREAD

**Issue by towoju5** [woocommerce/wc-api-php#299]
Automattic\WooCommerce\HttpClient\HttpClientException #301
JSON ERROR: Syntax error

**Comment by lucav** [comment]
Same here:

JSON ERROR: Syntax error

Automattic\WooCommerce\HttpClient\Request Object
(
    [url:Automattic\WooCommerce\HttpClient\Request:private] => https://crueltyfreecosmetics.biz/wp-json/wc/v3/products?per_page=100&page=1&consumer_key=ck_3b698db1b0f58d550122b29e2a7c0d1dfc0e558c&consumer_secret=cs_a6204451b6aafcde43d552c794f2882e61854566
    [method:Automattic\WooCommerce\HttpClient\Request:private] => GET
    [parameters:Automattic\WooCommerce\HttpClient\Request:private] => Array
        (
            [per_page] => 100
            [page] => 1
            [consumer_key] => ck_3b698db1b0f58d550122b29e2a7c0d1dfc0e558c
            [consumer_secret] => cs_a6204451b6aafcde43d552c794f2882e61854566
        )

    [headers:Automattic\WooCommerce\HttpClient\Request:private] => Array
        (
            [Accept] => application/json
            [User-Agent] => WooCommerce API Client-PHP/3.0.0
        )

    [body:Automattic\WooCommerce\HttpClient\Request:private] =>
)

Automattic\WooCommerce\HttpClient\Response Object
(
    [code:Automattic\WooCommerce\HttpClient\Response:private] => 302
    [headers:Automattic\WooCommerce\HttpClient\Response:private] => Array
        (
            [Date] => Tue, 20 Apr 2021 09:14:27 GMT
            [Content-Type] => text/html; charset=UTF-8
            [Content-Length] => 0
            [Connection] => keep-alive
            [Server] => nginx
            [Set-Cookie] => wp-wpml_current_admin_language_d249cdb4d32ab2db8328e7c284d5cc9c=en; expires=Wed, 21-Apr-2021 09:14:27 GMT; Max-Age=86400; path=/; domain=crueltyfreecosmetics.biz; secure
            [Location] => https://www.crueltyfreecosmetics.biz?aiowpsec_do_log_out=1&al_additional_data=1&_wpnonce=8a2fdaf0ba
        )

    [body:Automattic\WooCommerce\HttpClient\Response:private] =>
)

**Comment by lucav** [comment]
Same here:

JSON ERROR: Syntax error

Automattic\WooCommerce\HttpClient\Request Object
(
    [url:Automattic\WooCommerce\HttpClient\Request:private] => https://xxxxxx.biz/wp-json/wc/v3/products?per_page=100&page=1&consumer_key=xxxxxx&consumer_secret=xxxxxxxxxxxxx
    [method:Automattic\WooCommerce\HttpClient\Request:private] => GET
    [parameters:Automattic\WooCommerce\HttpClient\Request:private] => Array
        (
            [per_page] => 100
            [page] => 1
            [consumer_key] => xxxxxxxxxxxx
            [consumer_secret] => xxxxxxxxx
        )

    [headers:Automattic\WooCommerce\HttpClient\Request:private] => Array
        (
            [Accept] => application/json
            [User-Agent] => WooCommerce API Client-PHP/3.0.0
        )

    [body:Automattic\WooCommerce\HttpClient\Request:private] =>
)

Automattic\WooCommerce\HttpClient\Response Object
(
    [code:Automattic\WooCommerce\HttpClient\Response:private] => 302
    [headers:Automattic\WooCommerce\HttpClient\Response:private] => Array
        (
            [Date] => Tue, 20 Apr 2021 09:14:27 GMT
            [Content-Type] => text/html; charset=UTF-8
            [Content-Length] => 0
            [Connection] => keep-alive
            [Server] => nginx
            [Set-Cookie] => wp-wpml_current_admin_language_d249cdb4d32ab2db8328e7c284d5cc9c=en; expires=Wed, 21-Apr-2021 09:14:27 GMT; Max-Age=86400; path=/; domain=xxxxxxxxx.biz; secure
            [Location] => https://www.xxxxxx.biz?aiowpsec_do_log_out=1&al_additional_data=1&_wpnonce=8a2fdaf0ba
        )

    [body:Automattic\WooCommerce\HttpClient\Response:private] =>
)
