### ISSUE TITLE
Add __toString() for HttpClient@getResponse

### ISSUE THREAD

**Issue by LocalHeroPro** [woocommerce/wc-api-php#310]
Please add `__toString()` for HttpClient@getResponse.
Right now we have to 
```php
$a = print_r($client->http->getResponse(), true);
```
I think better option is to use
```php
$a = (string)$client->http->getResponse(); // Method '__toString' is not implemented for '\Automattic\WooCommerce\HttpClient\Response'
```
and store response in the log file.

**Comment by claudiosanches** [comment]
Hello @LocalHeroPro, 

Currently `HttpClient::getResponse` returns an instance of `Response` class. I don't think just using `print_r` will result in something useful. I'll implement it as JSON, so at least can be parsed and used properly later if required.

Thanks for your suggestion.
