### ISSUE TITLE
Fatal error: Uncaught Automattic\WooCommerce\HttpClient\HttpClientException: Error

### ISSUE THREAD

**Issue by atdheboshnjaku** [woocommerce/wc-api-php#313]
Hello there,

I am trying to create a plugin using the automattic/woocommerce package from packagist but I seem to be running into multiple errors since the beginning.

I am working on a local environment using MAMP, I have setup virtualhosts so my domain is:

http://woo.blu

I went ahead and:

`composer require automattic/woocommerce `

and I went ahead and created my woocommerce keys and am using them like this:

```
require __DIR__ . '/vendor/autoload.php';

use Automattic\WooCommerce\Client;

$woocommerce = new Client(
    'http://woo.blu/',
    'ck_892278d59d9b706576a076fc01c3104fddd1f79d',
    'cs_fabac459cf433b483101caf29019832321049341',
    [
        'wp_api' => true,
        'version' => 'wc/v3',
        'query_string_auth' => true, // Force Basic Authentication as query string true and using under HTTPS
        'timeout' => 400
    ]
);

print_r($woocommerce->get('products'));
```
but this gives me an error like this:

>Fatal error: Uncaught Automattic\WooCommerce\HttpClient\HttpClientException: Error: <p>There has been a critical error on this website.</p><p><a href="https://wordpress.org/support/article/faq-troubleshooting/">Learn more about troubleshooting WordPress.</a></p> [internal_server_error] in /Applications/MAMP/htdocs/woo/wp-content/plugins/woo/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php:350 Stack trace: #0 /Applications/MAMP/htdocs/woo/wp-content/plugins/woo/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php(386): Automattic\WooCommerce\HttpClient\HttpClient->lookForErrors(Object(stdClass)) #1 /Applications/MAMP/htdocs/woo/wp-content/plugins/woo/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php(422): Automattic\WooCommerce\HttpClient\HttpClient->processResponse() #2 /Applications/MAMP/htdocs/woo/wp-content/plugins/woo/vendor/automattic/woocommerce/src/WooCommerce/Client.php(82): Automattic\WooCommerce\HttpClient\HttpClient->request('products', 'GET', Array, Array) #3 /Applications/MAMP/htdocs/woo/wp-content/plugins/woo/woo.php(26): Automattic\WooCommerce\Client->get('products') #4 /Applications/MAMP/htdocs/woo/wp-settings.php(418): include_once('/Applications/M...') #5 /Applications/MAMP/htdocs/woo/wp-config.php(96): require_once('/Applications/M...') #6 /Applications/MAMP/htdocs/woo/wp-load.php(50): require_once('/Applications/M...') #7 /Applications/MAMP/htdocs/woo/wp-admin/admin.php(34): require_once('/Applications/M...') #8 {main} thrown in /Applications/MAMP/htdocs/woo/wp-content/plugins/woo/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php on line **350**

If I remove the `'timeout' => 400` then I get a different error like so:

>Fatal error: Uncaught Automattic\WooCommerce\HttpClient\HttpClientException: cURL Error: Operation timed out after 15001 milliseconds with 0 bytes received in /Applications/MAMP/htdocs/woo/wp-content/plugins/woo/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php:417 Stack trace: #0 /Applications/MAMP/htdocs/woo/wp-content/plugins/woo/vendor/automattic/woocommerce/src/WooCommerce/Client.php(82): Automattic\WooCommerce\HttpClient\HttpClient->request('products', 'GET', Array, Array) #1 /Applications/MAMP/htdocs/woo/wp-content/plugins/woo/woo.php(26): Automattic\WooCommerce\Client->get('products') #2 /Applications/MAMP/htdocs/woo/wp-settings.php(418): include_once('/Applications/M...') #3 /Applications/MAMP/htdocs/woo/wp-config.php(96): require_once('/Applications/M...') #4 /Applications/MAMP/htdocs/woo/wp-load.php(50): require_once('/Applications/M...') #5 /Applications/MAMP/htdocs/woo/wp-admin/admin.php(34): require_once('/Applications/M...') #6 {main} thrown in /Applications/MAMP/htdocs/woo/wp-content/plugins/woo/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php on line **417**

**Note**: I am also using pretty urls and I have searched almost everywhere for a solution. I tried to change the `'query_string_auth' => false`, I even tried to add `'ssl_verify' => false`. But nothing works. I also tried to include the httpexception like so:

`use Automattic\WooCommerce\HttpClient\HttpClientException;`

but it does not make a difference.

But I cannot seem to fine anything to get me out of this error and let me continue to develop. Please anyone that has been through this and found a solution/workaround share your knowledge.

Note: When I try to cURL using terminal like this:

`curl http://woo.blu/wp-json/wc/v3/products -u ck_892278d59d9b706576a076fc01c3104fddd1f79d:cs_fabac459cf433b483101caf29019832321049341`

it works fine, I get this response back in the terminal:

`[{"id":11,"name":"test product","slug":"test-product","permalink":"https:\/\/woo.blu\/product\/test-product\/","date_created":"2022-02-19T12:19:21","date_created_gmt":"2022-02-19T12:19:21","date_modified":"2022-02-19T12:19:21","date_modified_gmt":"2022-02-19T12:19:21","type":"simple","status":"publish","featured":false,"catalog_visibility":"visible","description":"<p>test description here<\/p>\n","short_description":"","sku":"","price":"12","regular_price":"12","sale_price":"","date_on_sale_from":null,"date_on_sale_from_gmt":null,"date_on_sale_to":null,"date_on_sale_to_gmt":null,"on_sale":false,"purchasable":true,"total_sales":0,"virtual":false,"downloadable":false,"downloads":[],"download_limit":-1,"download_expiry":-1,"external_url":"","button_text":"","tax_status":"taxable","tax_class":"","manage_stock":false,"stock_quantity":null,"backorders":"no","backorders_allowed":false,"backordered":false,"low_stock_amount":null,"sold_individually":false,"weight":"","dimensions":{"length":"","width":"","height":""},"shipping_required":true,"shipping_taxable":true,"shipping_class":"","shipping_class_id":0,"reviews_allowed":true,"average_rating":"0.00","rating_count":0,"upsell_ids":[],"cross_sell_ids":[],"parent_id":0,"purchase_note":"","categories":[{"id":15,"name":"Uncategorized","slug":"uncategorized"}],"tags":[],"images":[],"attributes":[],"default_attributes":[],"variations":[],"grouped_products":[],"menu_order":0,"price_html":"<span class=\"woocommerce-Price-amount amount\"><bdi><span class=\"woocommerce-Price-currencySymbol\">&#36;<\/span>12.00<\/bdi><\/span>","related_ids":[],"meta_data":[],"stock_status":"instock","_links":{"self":[{"href":"https:\/\/woo.blu\/wp-json\/wc\/v3\/products\/11"}],"collection":[{"href":"https:\/\/woo.blu\/wp-json\/wc\/v3\/products"}]}}]%`

hope this helps in pointing anything else out 🙂

**Comment by jdkumawat** [comment]
hello there
{
    "status": false,
    "error": {
        "classname": "Automattic\\WooCommerce\\HttpClient\\HttpClientException",
        "message": "cURL Error: SSL certificate problem: certificate has expired"
    }
}
please help with us

**Comment by claudiosanches** [comment]
Hello @atdheboshnjaku,

> Fatal error: Uncaught Automattic\WooCommerce\HttpClient\HttpClientException: Error:

This error happens because there's an exception uncaught by your code.
You should update to:

```php
require __DIR__ . '/vendor/autoload.php';

use Automattic\WooCommerce\Client;
use Automattic\WooCommerce\HttpClient\HttpClientException;

$woocommerce = new Client(
    'http://woo.blu/',
    'ck_892278d59d9b706576a076fc01c3104fddd1f79d',
    'cs_fabac459cf433b483101caf29019832321049341',
    [
        'wp_api' => true,
        'version' => 'wc/v3',
        'timeout' => 30
    ]
);

try {
    print_r($woocommerce->get('products'));
} catch (HttpClientException $e) {
    echo '<pre><code>' . print_r( $e->getMessage(), true ) . '</code><pre>'; // Error message.
    echo '<pre><code>' . print_r( $e->getRequest(), true ) . '</code><pre>'; // Last request data.
    echo '<pre><code>' . print_r( $e->getResponse(), true ) . '</code><pre>'; // Last response data.
}
```

> Note: I am also using pretty urls and I have searched almost everywhere for a solution. I tried to change the 'query_string_auth' => false, I even tried to add 'ssl_verify' => false. But nothing works. I also tried to include the httpexception like so:

Please check our docs for all options https://github.com/woocommerce/wc-api-php#client-class

Doesn't sounds like you need to use `query_string_auth` since your website doesn't use HTTPS anyway, so you should always use OAuth2 to connect, also `ssl_verify` is only use for Basic Auth. Both options aren't helpful for you.
Also a long timeout isn't a indication that the server is going to respond correctly, seems like in the first request is returning a server error.
Please try with the code I shared to you, it should give you more hints about how to use.

I'm closing for now since doesn't sounds like an issue on this library.
