### ISSUE TITLE
JSON ERROR: Syntax error / 403 Forbidden.

### ISSUE THREAD

**Issue by rayhvh** [woocommerce/wc-api-php#314]
Hello. For one of our customers the client does not seem to work. 

It is working for our other customers. And doing the same request in postman seems to work fine.

```
$products = $this->wooCommerceClient->get('products', [
    'per_page' => 50,
    'page' => $page,
    'status' => 'publish',
]);

```
initialize the client using:

```
        $this->wooCommerceClient = new Client(
            $connection->getUrl(),
            $connection->getApiKey(),
            $connection->getApiSecretKey(),
            [
                'version' => 'wc/v3',
            ]
        );
```

Ofcourse double checked the credentials.  

The url im using ive tried both with and without https:// as prefix. 
legacy api is disabled on woocommerce website. 

call being made :
wp-json/wc/v3/products?per_page=50&page=1&status=publish
or
wp-json/wc/v3/products?oauth_consumer_key=......&oauth_nonce=be53ead2f68a60844c6a809a34a3adbd05d96b62&oauth_signature=VDJU4l4Ss8%2B5HhOilf9iTDUSy3x6QbN9tQxFZwdCDaU%3D&oauth_signature_method=HMAC-SHA256&oauth_timestamp=1646214275&page=1&per_page=50&status=publish

The error body im getting back is:

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
</body></html>
```

**Comment by claudiosanches** [comment]
Hello @rayhvh,

> <p>You don't have permission to access this resource.</p>

This body seems very generic, there's many things that could trigger it, like Mod Security or another thing blocking requests with certainly headers.
You'll need to check the PHP error log and the server access log to properly debug it.

I'm closing for now because sadly there's nothing in this PHP library that I could change to help you with it.
