### ISSUE TITLE
Response headers not listing all links

### ISSUE THREAD

**Issue by rawcreative** [woocommerce/wc-api-php#35]
When accessing the response headers to view pagination data, I see that not all of the Link items are listed, only the last item which is typically the link to the last page of results, all other links are discarded. Looking at the code, they are just being overwritten here: https://github.com/woothemes/wc-api-php/blob/master/src/WooCommerce/HttpClient/HttpClient.php#L244

**Comment by claudiosanches** [comment]
All links are included in the response headers, if something is missing it's because your server is not sending.

**Comment by rawcreative** [comment]
No, they are not. Please test this before just closing the issue. 

Any api calls **not** using the new WP REST api integration return multiple Link headers on separate lines (WC adds each link as separate items in the headers, see lines 542-625 in class-wc-api-server.php in the legacy versions). The headers are then pushed into an array and then parsed via exploding and listing each item in that array. Because of this, duplicate Link entries are overwritten as I stated above.

**Comment by claudiosanches** [comment]
> Please test this before just closing the issue. 

I already tested and works just fine.

![screenshot from 2016-10-26 14-31-26](https://cloud.githubusercontent.com/assets/1264099/19735111/eeb50e82-9b88-11e6-9334-f79e422d73b6.png)

**Comment by rawcreative** [comment]
Per the url in your screenshot, you are testing on the v3 WP REST based api, NOT the legacy wc-api, like I stated in my last response.

**Comment by claudiosanches** [comment]
@rawcreative v3 is a legacy REST API and this test is in the new REST API integration.

**Comment by rawcreative** [comment]
Sorry @claudiosanches , I didn't mean to include the 'v3' in my last response. 

To clarify, the newest version of the WC API, which ships in WC 2.6+, is the **only** version that displays the links correctly. The legacy v3 api and the legacy v2 api DO NOT populate correctly using this lib due to the reasons I stated above. 

See the attached screenshot below, the top chunk is what is returned by the lib, the bottom is the raw headers.

![screen shot 2016-10-26 at 1 09 28 pm](https://cloud.githubusercontent.com/assets/1143718/19736513/9106ac7e-9b7d-11e6-8dd1-f609869fb327.png)

**Comment by claudiosanches** [comment]
@rawcreative more easy when you properly explain something.
