### ISSUE TITLE
Nonce invalid

### ISSUE THREAD

**Issue by Max84** [woocommerce/wc-api-php#40]
Hi,

This my php code:

```php
require __DIR__ . '/vendor/autoload.php';

use Automattic\WooCommerce\Client;

$woocommerce = new Client(
    $url, 
    $consumer_key, 
    $consumer_secret,
    [
        'version' => $version,
    ]
);

$parameters = array();
print_r($woocommerce->get('products', $parameters));
```

I always get this error:

> PHP Fatal error:  Uncaught exception 'Automattic\WooCommerce\HttpClient\HttpClientException' with message 'Error: Nonce invalide - le nonce a déjà été utilisé [woocommerce_api_authentication_error]' in C:\xampp\htdocs\Pour tests\woonlib\vendor\automattic\woocommerce\src\WooCommerce\HttpClient\HttpClient.php:315

Nonce is invalid.

Really strange. What happen ?

Thanks.

**Comment by claudiosmweb** [comment]
Trying with what version?

**Comment by Max84** [comment]
Hi,
I tested onto Woocommerce 2.3.7 (fresh install), 2.4.3 (Fresh Install), 2.5.5 (live site).
If needed, i can give to API key for fresh install, it's tests.

Thanks.

**Comment by daannet** [comment]
Hi @Max84,

Please check your client and WordPress server time. If this time has more than 15 minutes offset, the nonce is invalid.

**Comment by Max84** [comment]
Hi,

You might right, but maybe libs has a problem.

Libs uses php function time().
Check comments here : http://php.net/manual/fr/function.time.php

If server and client are uptime but uses several UTC time, nonce will be invalid. Won't it ?

Maybe libs should uses this
> $timestamp = time() - date('Z');

instead of time() (and wordpress too).

Best regards,

**Comment by claudiosmweb** [comment]
Have you checked it?
We can include an options for custom `oauth_timestamp`.

**Comment by Max84** [comment]
Hi,

Yes i checked it.
I saw this into OAuth.php file, near line 216:
`public function getParameters()
    {
        $parameters = \array_merge($this->parameters, [
            'oauth_consumer_key'     => $this->consumerKey,
            'oauth_timestamp'        => \time(),
            'oauth_nonce'            => \sha1(\microtime()),
            'oauth_signature_method' => 'HMAC-' . self::HASH_ALGORITHM,
        ]);`

Timestamp is hardcoded.
I thinked it can be hardcoded with array $options parameter into Client::__construct(), but this parameter seems to be used only for SSL, WP version, etc ... (i saw it into Options.php).
But not timestamp.

Am i wrong ?

Thanks.
