### ISSUE TITLE
Examples and Comparison

### ISSUE THREAD

**Issue by psasser** [woocommerce/wc-api-php#52]
Hello,

Currently I've built a plugin that creates/updates/deletes products in WooCommerce based on this [PHP library](https://github.com/kloon/WooCommerce-REST-API-Client-Library).  I see that you have contributed there as well.  Is this library these essentially doing the same thing as that one?  I'm interested in using this one as it seems to be updated a little more often.  Do you have any examples out there that show how to utilize this API to create products similar to [this](https://github.com/kloon/WooCommerce-REST-API-Client-Library/blob/master/example/example.php)?  Would your recommend one of these libraries over the other?  Thanks for you assistance.

Have a great day,
patrick

**Comment by claudiosmweb** [comment]
This is the official wrapper now and you can see examples in the WooCommerce REST API docs, under the PHP tab: https://woocommerce.github.io/woocommerce-rest-api-docs/

**Comment by psasser** [comment]
Thanks for the quick feedback.  I'm trying to implement this, but I'm not 100% sure how to do this.  Any help would be greatly appreciated.  I see that it uses composer, but I don't even really know what that is or how to implement that.  My thought was to download your Git files and then push to the server that I'm working on and then plugin the code from the readme, but that is referencing an autoload.php file which I obviously won't have.  Is there a way to install it without composer?  Or do you have a resource or video tutorial of how to user composer and then install this? Sorry to be such a noob at this.  

Thanks much,
patrick

**Comment by claudiosmweb** [comment]
@psasser the autoload.php is from Composer. Not that this is not a support channel.
If you need help, you should try the https://wordpress.org/support/plugin/woocommerce

> Is there a way to install it without composer?

Yes, you can include all classes manually.
