### ISSUE TITLE
Invalid Consumer Secret

### ISSUE THREAD

**Issue by Babelfisch** [woocommerce/wc-api-php#53]
I get a fatal error that my consumer secret should be invalid:

```Fatal error: Uncaught Automattic\WooCommerce\HttpClient\HttpClientException: Error: Consumer Secret ist ungültig [woocommerce_api_authentication_error]```

But consumer key and secret are correct (readonly) and the same keys working finde with other v3 API wrappers.

**Comment by claudiosmweb** [comment]
What WooCommerce version?
Show me how you are creating the instance.

**Comment by Babelfisch** [comment]
WooCommerce version 2.6.4
wc-api-php version 1.1.2 from GitHub

My test code for v3 API:

```php
require __DIR__ . '/vendor/autoload.php';
use Automattic\WooCommerce\Client;

$woocommerce = new Client(
    'https://shop.example.com', 
    'ck_…', 
    'cs_…',
    [
        'version' => 'v3',
    ]
);

$woocommerce->get('order/4801', $parameters = []);
```

Error: invalid consumer key

```
Fatal error: Uncaught exception 'Automattic\WooCommerce\HttpClient\HttpClientException' with message 'Error: Consumer Secret ist ungültig [woocommerce_api_authentication_error]' in /Users/…/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php:318
```

The same Consumer Key and Secret works fine with a other woocommerce-api wrapper. The keys are 100 percent correct.

**Comment by Babelfisch** [comment]
If I test it with the new REST API and `'query_string_auth' => true` parameter, it works fine with the same key and secret.

**Comment by claudiosmweb** [comment]
Yep, looks like your server don't set the auth headers, so it's best use the `query_string_auth` option.

Since using basic auth don't have any kind of issue with the parameters... I asked to show me how you are doing it, because generally I see this kind of issue using oAuth1.
