### ISSUE TITLE
Placing order for a specific customer 

### ISSUE THREAD

**Issue by koubeissy-ibrahim** [woocommerce/wc-api-php#54]
i'm building a mobile application to use with woocommerce, and my app should keep track of all the previous orders of the WP user (using the user id) 
was reading the documentation and found that when we create an order we don't specify the customer_id or the WP_USER the only related field is the email 

so my question is: 
1- Woo.customer = WP.user (wp_user.id = woo commerce customer_id) ?  
2- is it enaugh to specify the email of the WP user so that the order is created for this specific user ? 

Thanks

**Comment by claudiosmweb** [comment]
Don't looks like a question related to this REST API lib, so I'm closing and you should use a correct support channel for it.
