### ISSUE TITLE
Composer command not working to get dependency file 

### ISSUE THREAD

**Issue by ratnesh2581990** [woocommerce/wc-api-php#55]
Hello,
I am working on project which require use of Woocommerce Rest API for this I found your Tutorial and I followed it but I am Not able to get the dependency file using composer but every time it is showing wrong version error and minimum requirement not full filled error. i am using Xampp with php version 7 and curl and json enable. so please help me and guide me in proper way to use the API's

**Comment by claudiosanches** [comment]
Don't looks like an error with this project, looks like is something how you are trying to install this lib.
So sorry, but I can help you with composer, if you have questions about this lib I'll be happy to answer.

**Comment by ratnesh2581990** [comment]
when I installing I am getting following message in in command prompt 
"your requirement could not be resolved to an installable set of packages. 
Problem 1.
The requested package automattic/woocommerce No version set ( parsed as 1.0.0) is satisfiable by automattic/woocommerce [no version set(parsed as 1.0.0)] but these conflict with your requirements or minimum-stability "
This I am using Xampp With php 5.5.38. so can you please tell me where I am wrong or am I missing anything for installation of this library
