### ISSUE TITLE
variation images and featured image not adding while add product

### ISSUE THREAD

**Issue by tundak** [woocommerce/wc-api-php#56]
using data parameters same as reference http://woocommerce.github.io/woocommerce-rest-api-docs/#create-a-product but for variation it showing placeholder image after add product, same for featured image too.

**Comment by tundak** [comment]
![vriation](https://cloud.githubusercontent.com/assets/5101736/19702172/0911c12a-9b1c-11e6-9023-636a7f26ef4c.png)

**Comment by claudiosanches** [comment]
Don't looks like an problem with this REST API lib.
If you have questions with the WooCommerce REST API, you should use the WooCommerce support forum: https://wordpress.org/support/plugin/woocommerce
