### ISSUE TITLE
Rest API not showing the orders for the authentic user 

### ISSUE THREAD

**Issue by Shobby** [woocommerce/wc-api-php#57]
i am using WP Rest API to fetch the orders from store using consumer key and secrete in URL but its giving me error of permission and order not be read. I am using WP version 4.6.1 and WC version 2.6

When Request to get the order using my Consumer Key and Secrete with HTTPS request its says some permission errors ass follows

https://www.onetwocosmetics.com/wc-api/v3/orders/8082?consumer_key=MY_CONSUMER_KEY&consumer_secret=MY_CONSUMER_SECRETE

ERROR:
{“errors”:[{“code”:”woocommerce_api_user_cannot_read_order”,”message”:”You do not have permission to read this order”}]}

But when i tried to get the products with the same credentials it gives me the correct results as follows:

https://www.onetwocosmetics.com/wc-api/v3/products/?consumer_key=MY_CONSUMER_KEY&consumer_secret=MY_CONSUMER_SECRETE

**Comment by claudiosanches** [comment]
Not an issue with this REST API lib.
Looks like you user don't have permissions to read orders, only products, maybe something that you need to fix in your installation.

**Comment by Shobby** [comment]
I have set read-write permission for the user then what is the issue?

**Comment by Shobby** [comment]
Is there any special permission i have to set to get the orders?

**Comment by claudiosanches** [comment]
Not that this is not an issue with this REST API lib.
You should use the WooCommerce support forum: https://wordpress.org/support/plugin/woocommerce
