### ISSUE TITLE
'Error: Sorry, you cannot list resources. [woocommerce_rest_cannot_view]'

### ISSUE THREAD

**Issue by RobertoDonPedro** [woocommerce/wc-api-php#59]
Hi, I get this error in wc-api and Postman with basic authentication. My Server is hosted in google cloud services (should not be to special..) and I run the latest wc versions, etc:
'Error: Sorry, you cannot list resources. [woocommerce_rest_cannot_view]'

**With `'query_string_auth' => true` everthing works fine.**

However, seems that other clients do not support this setting. 
Does anyone know how to fix this issue in Postman and/or on the server?

**Comment by RobertoDonPedro** [comment]
Further explanation:
It even does not work with the curl command outlined in the WooCommerce REST API Doku  for servers that do not properly parse the Authorization header:
http://woocommerce.github.io/woocommerce-rest-api-docs/?shell#rest-api-keys

`curl https://www.example.com/wp-json/wc/v1/orders?consumer_key=123&consumer_secret=abc`

In addition to the previous reported error message this message is returned with curl: 
The command "consumer_secret" is either misspelled or could not be found

Please help, the WooCommerce REST APIs can just be used on a professional basis, if all clients can be served.
Thx, Robert

**Comment by RobertoDonPedro** [comment]
Update: 
This works with Postman, but not with curl:
`curl https://www.example.com/wp-json/wc/v1/orders?consumer_key=123&consumer_secret=abc`
Error message with curl: The command "consumer_secret" is either misspelled or could not be found

**Comment by claudiosanches** [comment]
> With 'query_string_auth' => true everthing works fine.

It's because your server is not parsing the `HTTP_AUTHENTICATION` header into `$_SERVER['PHP_AUTH_USER']` and `$_SERVER['PHP_AUTH_PW']`.

This is an issue with your server and not with this REST API lib or WooCommerce.
