### ISSUE TITLE
404 Error ... or something

### ISSUE THREAD

**Issue by psasser** [woocommerce/wc-api-php#62]
I'm getting this error code and I'm not sure why.  I have the same code on another site/server and it is working just fine.  http://pastebin.com/yKQ5RcJE

Any thoughts or help would be much appreciated.

**Comment by claudiosanches** [comment]
Don't looks like an issue with this REST API wrapper.
If you have questions or issues with the WooCommerce REST API you should try https://wordpress.org/support/plugin/woocommerce
