### ISSUE TITLE
How to disable error reporting ?

### ISSUE THREAD

**Issue by abhishekdeshkar** [woocommerce/wc-api-php#63]
Hello,
I'm trying to push product in the database even if the sku already exists. I still want to execute script if sku exists it should ignore. But it has stopped the script. I tried to disable error reporting with ```error_reporting(0)``` and ```ini_set("display_errors",0)``` but didn't work. How can I disable this error reporting and run script continuously ?

Current error :

```
Array ( [errors] => Array ( [0] => Array ( [code] => woocommerce_api_product_sku_already_exists [message] => The SKU already exists on another product ) ) )
```

Thanks!

**Comment by claudiosanches** [comment]
This is the response from WooCommerce and when this wrapper catch turns as an Exception and you can handle it. It's not a "PHP fatal error" or warning.

> I'm trying to push product in the database even if the sku already exists

And WooCommerce does not allow create products with the same SKU.
