### ISSUE TITLE
WooCommerce Rest API Client Library with PHP , localhost GET is not working

### ISSUE THREAD

**Issue by Lavkushwaha** [woocommerce/wc-api-php#65]
Input:
index.php
```php
<?php
require __DIR__ . '/vendor/autoload.php';

use Automattic\WooCommerce\Client;

$woocommerce = new Client(
    'https://babaplant.com',
    'ck_dfcffd5ea168a907250d6c031597575c3d7b32b9',
    'cs_c8e18f24a0d799e76af89e4058946c5c4ea78e25',
    [
        'wp_api' => true,
        'version' => 'wc/v1',
		'query_string_auth' => true,
		'verify_ssl' => false
    ]
);
print_r($woocommerce->get(''));
?>
```

Output:
[api framework.zip](https://github.com/woocommerce/wc-api-php/files/608205/api.framework.zip)

"Fatal error: Uncaught Automattic\WooCommerce\HttpClient\HttpClientException: Syntax error in C:\xampp\htdocs\vendor\automattic\woocommerce\src\WooCommerce\HttpClient\HttpClient.php:336 Stack trace: #0 C:\xampp\htdocs\vendor\automattic\woocommerce\src\WooCommerce\HttpClient\HttpClient.php(375): Automattic\WooCommerce\HttpClient\HttpClient->processResponse() #1 C:\xampp\htdocs\vendor\automattic\woocommerce\src\WooCommerce\Client.php(82): Automattic\WooCommerce\HttpClient\HttpClient->request('', 'GET', Array, Array) #2 C:\xampp\htdocs\index.php(17): Automattic\WooCommerce\Client->get('') #3 {main} thrown in C:\xampp\htdocs\vendor\automattic\woocommerce\src\WooCommerce\HttpClient\HttpClient.php on line 336"

**Comment by bryceadams** [comment]
Likely issue on your site, check the store's error logs to see.

**Comment by Lavkushwaha** [comment]
if their is any error due to localhost XAMPP . or i have to test these API in hosting server.?

**Comment by bryceadams** [comment]
It should work with localhost - try disable all plugins besides WC and switch to default theme.

**Comment by Lavkushwaha** [comment]
see this is my error log.
[error_log.txt](https://github.com/woocommerce/wc-api-php/files/608216/error_log.txt)

**Comment by Lavkushwaha** [comment]
maybe i am not able to communicate with WC rest API, cause their is no error in error_log on date.
can you help me to make a connection through localhost to WooCommerce Rest API, i am new to these APIs and Vendors , Autoload & Automattic stuff.

**Comment by Lavkushwaha** [comment]
got same error again.


Fatal error: Uncaught exception 'Automattic\WooCommerce\HttpClient\HttpClientException' with message 'Syntax error' in /home/dweb/public_html/websites/incals.in/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php:336 Stack trace: #0 /home/dweb/public_html/websites/incals.in/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php(375): Automattic\WooCommerce\HttpClient\HttpClient->processResponse() #1 /home/dweb/public_html/websites/incals.in/vendor/automattic/woocommerce/src/WooCommerce/Client.php(82): Automattic\WooCommerce\HttpClient\HttpClient->request('', 'GET', Array, Array) #2 /home/dweb/public_html/websites/incals.in/index.php(17): Automattic\WooCommerce\Client->get('') #3 {main} thrown in /home/dweb/public_html/websites/incals.in/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php on line 336

**Comment by Lavkushwaha** [comment]
*https://url; cause this previous error.... now changed to http://url; & 'verify_ssl' => false"

then we have-


Fatal error: Uncaught Automattic\WooCommerce\HttpClient\HttpClientException: Error: Invalid timestamp. [woocommerce_rest_authentication_error] in C:\xampp\htdocs\vendor\automattic\woocommerce\src\WooCommerce\HttpClient\HttpClient.php:320 Stack trace: #0 C:\xampp\htdocs\vendor\automattic\woocommerce\src\WooCommerce\HttpClient\HttpClient.php(339): Automattic\WooCommerce\HttpClient\HttpClient->lookForErrors(Array) #1 C:\xampp\htdocs\vendor\automattic\woocommerce\src\WooCommerce\HttpClient\HttpClient.php(375): Automattic\WooCommerce\HttpClient\HttpClient->processResponse() #2 C:\xampp\htdocs\vendor\automattic\woocommerce\src\WooCommerce\Client.php(82): Automattic\WooCommerce\HttpClient\HttpClient->request('', 'GET', Array, Array) #3 C:\xampp\htdocs\index.php(18): Automattic\WooCommerce\Client->get('') #4 {main} thrown in C:\xampp\htdocs\vendor\automattic\woocommerce\src\WooCommerce\HttpClient\HttpClient.php on line 320

**Comment by Lavkushwaha** [comment]
next step with try and catch-
code:
<?php
require __DIR__ . '/vendor/autoload.php';

use Automattic\WooCommerce\Client;

$woocommerce = new Client(
    'http://url',
    'ck_####',
    'cs_####',
    [
        'wp_api' => true,
        'version' => 'wc/v1',
		'query_string_auth' => true,
		'verify_ssl' => false
    ]
);

use Automattic\WooCommerce\HttpClient\HttpClientException;

try{

print_r($woocommerce->get('products'));

}catch(HttpClientException $e){

\print_r($e);

\print_r($e->getMessage() . PHP_EOL);

\print_r('Code: ' . $e->getResponse()->getCode() . PHP_EOL);

\print_r('Body: ' . $e->getResponse()->getBody() . PHP_EOL);

}

?>

output:

.
.
.
.
C:\xampp\htdocs\vendor\automattic\woocommerce\src\WooCommerce\HttpClient\HttpClient.php [line] => 339 [function] => lookForErrors [class] => Automattic\WooCommerce\HttpClient\HttpClient [type] => -> [args] => Array ( [0] => Array ( [code] => woocommerce_rest_authentication_error [message] => Invalid timestamp. [data] => Array ( [status] => 401 ) ) ) ) [1] => Array ( [file] => C:\xampp\htdocs\vendor\automattic\woocommerce\src\WooCommerce\HttpClient\HttpClient.php [line] => 375 [function] => processResponse [class] => Automattic\WooCommerce\HttpClient\HttpClient [type] => -> [args] => Array ( ) ) [2] => Array ( [file] => C:\xampp\htdocs\vendor\automattic\woocommerce\src\WooCommerce\Client.php [line] => 82 [function] => request [class] => Automattic\WooCommerce\HttpClient\HttpClient [type] => -> [args] => Array ( [0] => products [1] => GET [2] => Array ( ) [3] => Array ( ) ) ) [3] => Array ( [file] => C:\xampp\htdocs\index.php [line] => 22 [function] => get [class] => Automattic\WooCommerce\Client [type] => -> [args] => Array ( [0] => products ) ) ) [previous:Exception:private] => ) Error: Invalid timestamp. [woocommerce_rest_authentication_error] Code: 401 Body: {"code":"woocommerce_rest_authentication_error","message":"Invalid timestamp.","data":{"status":401}}

**Comment by claudiosanches** [comment]
```Fatal error: Uncaught Automattic\WooCommerce\HttpClient\HttpClientException```

Some error on your store, so is throwing exceptions and you are catching anything...

Here an example catching exceptions: https://github.com/woocommerce/wc-api-php#response

**Comment by claudiosanches** [comment]
And here the real error message:

```json
{"code":"woocommerce_rest_authentication_error","message":"Invalid timestamp.","data":{"status":401}}
```

**Comment by Lavkushwaha** [comment]
thanx

**Comment by Lavkushwaha** [comment]
i am getting results but seems not like in Proper JSON format;


Array ( [0] => Array ( [id] => 15 [name] => Logo T-shirt [slug] => logo-t-shirt [permalink] => http://incals.in/product/logo-t-shirt/ [date_created] => 2016-11-23T11:28:27 [date_modified] => 2016-11-23T11:28:28 [type] => simple [status] => publish [featured] => [catalog_visibility] => visible [description] =>
This is a sample product description.

[short_description] =>
This is a short description.

[sku] => [price] => 18 [regular_price] => 20 [sale_price] => 18 [date_on_sale_from] => [date_on_sale_to] => [price_html] => $20.00 $18.00 [on_sale] => 1 [purchasable] => 1 [total_sales] => 0 [virtual] => [downloadable] => [downloads] => Array ( ) [download_limit] => -1 [download_expiry] => -1 [download_type] => standard [external_url] => [button_text] => [tax_status] => taxable [tax_class] => [manage_stock] => 1 [stock_quantity] => 5 [in_stock] => 1 [backorders] => no [backorders_allowed] => [backordered] => [sold_individually] => [weight] => [dimensions] => Array ( [length] => [width] => [height] => ) [shipping_required] => 1 [shipping_taxable] => 1 [shipping_class] => [shipping_class_id] => 0 [reviews_allowed] => 1 [average_rating] => 4.00 [rating_count] => 1 [related_ids] => Array ( [0] => 50 [1] => 37 [2] => 34 ) [upsell_ids] => Array ( [0] => 60 ) [cross_sell_ids] => Array ( ) [parent_id] => 0 [purchase_note] => [categories] => Array ( [0] => Array ( [id] => 9 [name] => Clothing [slug] => clothing ) [1] => Array ( [id] => 14 [name] => T-shirts [slug] => t-shirts ) ) [tags] => Array ( ) [images] => Array ( [0] => Array ( [id] => 172 [date_created] => 2016-11-23T11:28:27 [date_modified] => 2016-11-23T11:28:28 [src] => http://incals.in/wp-content/uploads/2016/11/logo_tee_front.jpg [name] => Logo T-shirt [alt] => [position] => 0 ) [1] => Array ( [id] => 172 [date_created] => 2016-11-23T11:28:27 [date_modified] => 2016-11-23T11:28:28 [src] => http://incals.in/wp-content/uploads/2016/11/logo_tee_front.jpg [name] => Logo T-shirt [alt] => [position] => 1 ) [2] => Array ( [id] => 173 [date_created] => 2016-11-23T11:28:27 [date_modified] => 2016-11-23T11:28:28 [src] => http://incals.in/wp-content/uploads/2016/11/logo_tee_back.jpg [name] => Logo T-shirt [alt] => [position] => 2 ) ) [attributes] => Array ( ) [default_attributes] => Array ( ) [variations] => Array ( ) [grouped_products] => Array ( ) [menu_order] => 0 [_links] => Array ( [self] => Array ( [0] => Array ( [href] => http://incals.in/wp-json/wc/v1/products/15 ) ) [collection] => Array ( [0] => Array ( [href] => http://incals.in/wp-json/wc/v1/products ) ) ) ) [1] => Array ( [id] => 34 [name] => Ninja T-shirt [slug] => ninja-t-shirt [permalink] => http://incals.in/product/ninja-t-shirt/ [date_created] => 2016-11-23T11:28:27 [date_modified] => 2016-11-23T11:28:28 [type] => simple [status] => publish [featured] => [catalog_visibility] => visible [description] =>
This is a sample product description.

[short_description] =>
This is a short description.
.
.
.


what kind of JSON it is ?
even i hv tried these too
 http://json-schema.org/example1.html
www.jsoneditoronline.org/
& got nothing but ERRORS

**Comment by Lavkushwaha** [comment]
for Reference try yourself:
incals.in/api 

*temp purpose.. webpage no longer will be available

**Comment by Lavkushwaha** [comment]
for Solution https://github.com/woocommerce/wc-api-php/issues/65

**Comment by ranjeetpatel92** [comment]
Any help would be appreciated.

Using postman and hit this url: http://localhost/woorestapi/wp-json/wc/v1/products
O/p: {
  "code": "woocommerce_rest_cannot_view",
  "message": "Sorry, you cannot list resources.",
  "data": {
    "status": 401
  }
}
I m New here and not able to get the products details in json format.

**Comment by saifrehman15** [comment]
I have got the almost same issue while creating the webhook using woocommerce rest api. I got following error.

**Comment by claudiosanches** [comment]
@saifrehman15 it's not the same issue, you are not sending the webhook data as the reported in the error.
