### ISSUE TITLE
Error: Invalid JSON body passed

### ISSUE THREAD

**Issue by peterigz** [woocommerce/wc-api-php#68]
Originally reported here: (https://core.trac.wordpress.org/ticket/39166) and continued here: (https://core.trac.wordpress.org/ticket/39150#comment:4)

Since 4.7 I can no longer do a request with the php wrapper (https://github.com/woocommerce/wc-api-php), so doing:

`$order = $client->get('orders/'.$order_id);`

I get the error "Error: Invalid JSON body passed". The body being passed is of course blank because there's no data needed for a get request.

It's been suggested that maybe it's possible to avoid passing the content-type header in certain instances?

**Comment by bryceadams** [comment]
Confirmed

**Comment by bryceadams** [comment]
@claudiosanches I ended up making the following change - https://github.com/bryceadams/wc-api-php/commit/7b27f5e346a7bfed47df987fedab77dc65f51923 - seems to work, if you'd like I can PR with it but tests also need to be updated too.

Excludes content type if no body - if have body, sets it.

Seem ok?

**Comment by mikejolley** [comment]
Should be. Does sound like a WP issue though - even insomnia client triggers this error unless you choose plain text.

**Comment by bryceadams** [comment]
@mikejolley definitely WP 4.7 issue - I think they have a patch ready for next release, so this may be irrelevant, but I'm already using my version to support current 4.7 users.

**Comment by trajche** [comment]
@peterigz Thanks for opening this ticket - was starting to lose my mind. @bryceadams Thanks for the fix will try it now...

**Comment by bryceadams** [comment]
@trajche for now you can add the following to your `composer.json` and run `composer update`:

```
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/bryceadams/wc-api-php"
        }
    ]
```

**Comment by trajche** [comment]
@bryceadams Thanks! It's working!

**Comment by fpetkovski** [comment]
You need to add the specific commit in your package reference like so:
"automattic/woocommerce": "dev-master#7b27f5e346a7bfed47df987fedab77dc65f51923",

**Comment by bryceadams** [comment]
@fpetkovski it's normally best to do it like I mentioned so it takes the latest version from my package. When we get a decision from mike/claudio re: solution (guys, feel free to just use mine / modify it a bit so it's cleaner or whatever's easier, or I can make a PR tomorrow), and then the changes get put back into the main package, you'd remove the extra repositories part from above and run update to get the latest.

**Comment by fpetkovski** [comment]
Ok @bryceadams, thanks for the heads up

**Comment by claudiosanches** [comment]
Fixed in version 1.1.4, thanks for report it.

**Comment by i-make-robots** [comment]
Hi!  I'm using WP 4.7 + WC 2.6.11 and getting this error.  I don't yet understand the fix.  Please explain further?

**Comment by bryceadams** [comment]
@i-make-robots use the latest version of this library.

**Comment by i-make-robots** [comment]
tyvm @bryceadams !
