### ISSUE TITLE
meta_query not supported . Invalid signature Error

### ISSUE THREAD

**Issue by chiluhimanshu2221** [woocommerce/wc-api-php#69]
As soon as we pass **meta_query** in filter argument for products . It throws a invalid signature exception.

`$woocommerce->get('products',array('filter'=>array('meta_query'=>array('key'=>'_price','value'=>8))));

Automattic\WooCommerce\Client Object ( [http] => Automattic\WooCommerce\HttpClient\HttpClient Object ( [ch:protected] => [url:protected] => http://{myapiurl}/wp-json/wc/v1/ [consumerKey:protected] => ck_5d608fdcea615af2de7a9f2a91a63ded911d32f8 [consumerSecret:protected] => cs_ccaecf46305de138081bbb01d5f7a2d37197ac00 [options:protected] => Automattic\WooCommerce\HttpClient\Options Object ( [options:Automattic\WooCommerce\HttpClient\Options:private] => Array ( [wp_api] => 1 [version] => wc/v1 ) ) [request:Automattic\WooCommerce\HttpClient\HttpClient:private] => [response:Automattic\WooCommerce\HttpClient\HttpClient:private] => [responseHeaders:Automattic\WooCommerce\HttpClient\HttpClient:private] => ) )

Fatal error:  Uncaught exception 'Automattic\WooCommerce\HttpClient\HttpClientException' with message 'Error: Invalid Signature - provided signature does not match. [woocommerce_rest_authentication_error]' in /var/www/html/restapi/wc-api-php/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php:320
Stack trace:
#0 /var/www/html/restapi/wc-api-php/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php(339): Automattic\WooCommerce\HttpClient\HttpClient->lookForErrors(Array)
#1 /var/www/html/restapi/wc-api-php/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php(375): Automattic\WooCommerce\HttpClient\HttpClient->processResponse()
#2 /var/www/html/restapi/wc-api-php/vendor/automattic/woocommerce/src/WooCommerce/Client.php(82): Automattic\WooCommerce\HttpClient\HttpClient->request('products', 'GET', Array, Array)
#3 /var/www/html/restapi/wc-api-php/test.php(22): Automattic\WooCommerce\Client->get('products', Array)
#4 {main}
  thrown in /var/www/html/restapi/wc-api-php/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php on line 320
`
However while looking into **woocommerce_rest_query_vars** hook meta_query is already present in valid vars. The filter is working with meta_key,meta_value individually but it is not supporting **meta_query**

**Comment by claudiosanches** [comment]
This REST API lib is unable to "not supported" anything, if the WooCommerce REST API supports something, this lib will support too.

> Fatal error: Uncaught exception 'Automattic\WooCommerce\HttpClient\HttpClientException' with message 'Error: Invalid Signature - provided signature does not match.

This happens because need to sort it first as we say on the WooCommerce REST API docs.
