### ISSUE TITLE
I got http exception

### ISSUE THREAD

**Issue by dhdhxk** [woocommerce/wc-api-php#70]
Hi.

It worked fine, but I don`t know why, it got error.

Fatal error: Uncaught exception 'Automattic\WooCommerce\HttpClient\HttpClientException' with message 'Error: []' in C:\xampp\htdocs\woocommerce\vendor\automattic\woocommerce\src\WooCommerce\HttpClient\HttpClient.php:320 Stack trace: #0 C:\xampp\htdocs\woocommerce\vendor\automattic\woocommerce\src\WooCommerce\HttpClient\HttpClient.php(339): Automattic\WooCommerce\HttpClient\HttpClient->lookForErrors(NULL) #1 C:\xampp\htdocs\woocommerce\vendor\automattic\woocommerce\src\WooCommerce\HttpClient\HttpClient.php(375): Automattic\WooCommerce\HttpClient\HttpClient->processResponse() #2 C:\xampp\htdocs\woocommerce\vendor\automattic\woocommerce\src\WooCommerce\Client.php(82): Automattic\WooCommerce\HttpClient\HttpClient->request('orders', 'GET', Array, Array) #3 C:\xampp\htdocs\woocommerce\getOrders.php(44): Automattic\WooCommerce\Client->get('orders', Array) #4 {main} thrown in C:\xampp\htdocs\woocommerce\vendor\automattic\woocommerce\src\WooCommerce\HttpClient\HttpClient.php on line 320

Can you check why it happened?

Thanks!

**Comment by claudiosanches** [comment]
Well, first this fatal error is because you are catching any exceptions that this lib is throwing.
So will be a first good start for you if you start properly with exceptions.
