### ISSUE TITLE
Custom fields

### ISSUE THREAD

**Issue by abhishekdeshkar** [woocommerce/wc-api-php#71]
Hello,

How can I fetch orders with custom fields ? For example,

```
/wp-json/wc/v1/orders?filter[meta_key]=your_meta_key&filter[meta_value]=required_meta_value
```

I tried this but didn't work.
```
$woocommerce->options("orders?filter[meta]=true");
```

Thanks!

**Comment by claudiosanches** [comment]
Looks like you should read the REST API docs: https://woocommerce.github.io/woocommerce-rest-api-docs/
And `OPTIONS` request don't accept any query string parameters.
