### ISSUE TITLE
Route with count does not exist

### ISSUE THREAD

**Issue by grzegorz-lech** [woocommerce/wc-api-php#72]
Hi.

I try to get orders count by calling: 
`$woocommerce->get('orders/count');`

but I'm getting error:
`Error: No route was found matching the URL and request method [rest_no_route]`

I also call:
`$woocommerce->get('/');`

where I receive all routes but there is no information how can I get counter of all orders.

Can someone tell me what I'm doing wrong?

**Comment by claudiosanches** [comment]
Using the lasted REST API?
Because the new REST API don't have any `count` endpoint anymore.
You can check the docs for all REST API versions in https://woocommerce.github.io/woocommerce-rest-api-docs/
