### ISSUE TITLE
Add to cart, Checkout and Pay with Paypal

### ISSUE THREAD

**Issue by tanxeel** [woocommerce/wc-api-php#73]
I am developing a mobile app API using this Library.
I need Some necessary function required for this API including 
1) How can I add a Product to Cart?
2) How can I do Checkout process?
3) How can I add a payment method, i.e., PayPal in rest API?

If I can do this using 'Order' endpoint can someone elaborate how I can do this using any example?
It will be something like a user click on product for add to cart then checkout and at an end for pay amount using PayPal account, same like wooCommerce website process.
Or if anyone has already created API for mobile, 
please share here or email me at tanxeel@outlook.com
Thank you

**Comment by claudiosanches** [comment]
Sorry, but here is not a support channel for the WooCommerce REST API, if you have questions or problems related to the `wc-api-php` REST API lib I'll happy to help you.

**Comment by tanxeel** [comment]
Yes @claudiosanches my question is related to `wc-api-php` library. i am using this library and having above issue in this can you help me please.
