### ISSUE TITLE
Need help for Improving Perfmance

### ISSUE THREAD

**Issue by damianpna88** [woocommerce/wc-api-php#78]
Hi, in my company we are developing a tool to move data(clients, products, brands, categorys...etc) from a db into woocommerce using the REST API.
We are having a huge issue, inserting each item (clients, products,... whatever) takes between 4 to 5 seconds. So, doing the full movement of data takes around an hour. 
We also try using a non official api [(https://github.com/kloon/WooCommerce-REST-API-Client-Library)],that for our surprise its faster, around 3 secons for each insertion.(It still is too much time).
We would like to know if there is some way to speed this up.
Thanks

**Comment by claudiosanches** [comment]
You always can not use this REST API lib and write your own code to do it.
And I can't see how this lib can slow down it. Anyway good luck.
