### ISSUE TITLE
How filter orders between dates?

### ISSUE THREAD

**Issue by ricardocanelas** [woocommerce/wc-api-php#81]
Hi,

How can we filter some orders? or How can we use the param 'filter'? 
For example: I would like filter order between some dates (2017-01-01 and 2017-02-01)

```php
$woocommerce->get('orders',  ['per_page' => '30', 'page' => '1', 'status' => 'completed']);
```

Thanks, 
Ricardo

**Comment by pixelpeter** [comment]
`filter` will be deprecated in future versions of the Woocoomerce REST API.
Use `before` and `after` with an ISO-8601 compliant date.

**Comment by ricardocanelas** [comment]
Thanks! It's working with 'after' and 'before'
