### ISSUE TITLE
Best Practice to share API keys with customers

### ISSUE THREAD

**Issue by RobertoDonPedro** [woocommerce/wc-api-php#84]
Hi, 
I am building
1) extendend web services running on my server and 
2) plug-ins running on my customers servers accessing the APIs on my server

I am wondering if there is a best practice how to share the API keys created on my server (1) with the customers using the plug-ins (2) on their server.

Hardcoding the keys in the plugin like in the samples seems not possible, since every customer must have access to just his resources. Making the customers entering his keys in the Plugins Settings would be an option, but how do they get the keys? Sending the key by email probably is probably not a good idea.

I assume that auto-generation of keys by customers by using /wc-auth/v1/authorize in the plugins is not designed for this purpose, since the customer would need 'manage_woocommerce' capabilities on my server then (according to the code in WC_Auth Class),

Are there any best practices for this process available? Any hint is very appreciated.
Thank you!

**Comment by claudiosanches** [comment]
Sorry, but here is not a support channel for the WooCommerce REST API.
