### ISSUE TITLE
Error Invalid Signature

### ISSUE THREAD

**Issue by Mehrdad1991h** [woocommerce/wc-api-php#86]
I try to use from this lib with `HTTP` so for test installed new `Wordpress` , installed `WooCommerce` change `Permalink ` create `api key` with read/write permission and then
here is my code 

```
require __DIR__ . '/vendor/autoload.php';

use Automattic\WooCommerce\Client;

$woocommerce = new Client(
    'http://sample.com', 
    'ck_9f06003ed0b00901076becde8d7d23728f6a4c0f', 
    'cs_49aac2266add300bc4b7bafaf879ba1eb8f69be2',
    [
         'wp_api' => true,
        'version' => 'wc/v1',
    ]
);

print_r($woocommerce->GET('/wp-json/wc/v1/products/categories'));
```

But always return 

> Error: Invalid Signature - provided signature does not match. [woocommerce_rest_authentication_error

really why ? when i don't have `HTTPS` I can't use from this lib ? why ?

**Comment by claudiosanches** [comment]
Just follow the REST API docs: https://woocommerce.github.io/woocommerce-rest-api-docs/
Here is not a support channel for the REST API, but look that you suppose to not include `/wp-json/wc//v1/` in the request.
