### ISSUE TITLE
unexpected character on post new product

### ISSUE THREAD

**Issue by 2aviv20** [woocommerce/wc-api-php#89]
when I use `print_r($woocommerce->get($productNumber)); ` it  works I recive the product.
but when I am trying to post new one I recive unexpected character 

wp version 4.7
woocommerce version 2.6.14

vagrant scotchbox
============
PHP Version 5.6.14
MySQL Version 5.5.46

`<?php
require 'vendor/autoload.php';
use Automattic\WooCommerce\Client;
use Automattic\WooCommerce\HttpClient\HttpClientException;

$woocommerce = new Client(
    'http://192.168.33.10/',
    'ck_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'cs_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    [
        'wp_api' => true,
        'version' => 'wc/v1',
    ]
);

$data = [
    'name' => 'Premium Quality',
    'type' => 'simple',
    'regular_price' => '21.99',
    'description' => 'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.',
    'short_description' => 'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.',
    'categories' => [
        [
            'id' => 9
        ],
        [
            'id' => 14
        ]
    ],
    'images' => [
        [
            'src' => 'http://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2013/06/T_2_front.jpg',
            'position' => 0
        ],
        [
            'src' => 'http://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2013/06/T_2_back.jpg',
            'position' => 1
        ]
    ]
];

try {
    print_r($woocommerce->post('products', $data));
} catch(HttpClientException $e) {
    \print_r($e->getMessage());
}

?>
`

**Comment by claudiosanches** [comment]
Don't looks like an issue with this REST API lib.
Check your implementation before.
