### ISSUE TITLE
Unable to create product using REST API

### ISSUE THREAD

**Issue by routbiplab** [woocommerce/wc-api-php#94]
I am using Basic Oauth 1.0. Still getting the error.
{
  "errors": [
    {
      "code": "woocommerce_api_authentication_error",
      "message": "Consumer Key is missing"
    }
  ]
}

**Comment by claudiosanches** [comment]
Because is still missing the consumer key.
This wrap works just fine with any version of the WooCommerce REST API.
Just need to follow the docs and set up it properly.
Closing since it's not an issue with this REST API lib.
