### ISSUE TITLE
Unable to create new product using REST API

### ISSUE THREAD

**Issue by routbiplab** [woocommerce/wc-api-php#95]
WP: **4.7**
WC : **2.6.2**

HTTP Request : `POST : https://frontend/wc-api/v2/products?consumer_key=ck_somestring&consumer_secret=cs_somestring`
Authorization : **No Auth**
Body : 

> {
>   "product": {
>     "title": "Premium Quality",
>     "type": "simple",
>     "regular_price": "21.99",
>     "description": "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
>     "short_description": "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.",
>   
>     "images": [
>       {
>         "src": "http://example.com/wp-content/uploads/2015/01/premium-quality-front.jpg",
>         "position": 0
>       },
>       {
>         "src": "http://example.com/wp-content/uploads/2015/01/premium-quality-back.jpg",
>         "position": 1
>       }
>     ]
>   }
> }

Expected result : **New product is created with proper response.**
Actual result : **New product is not created and it is returning product all list response.**

**Comment by claudiosanches** [comment]
Sorry, but for what you are reporting, don't looks like a issue with this REST API lib.
You should try the support channel: https://wordpress.org/support/plugin/woocommerce
