### ISSUE TITLE
Can't install via composer

### ISSUE THREAD

**Issue by thgiang** [woocommerce/wc-api-php#96]
C:\xampp\htdocs\wc>composer require automattic/woocommerce:~1.2.0

./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package automattic/woocommerce No version set (parsed as 1.0.0) is satisfiable by automattic/woocommerce[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.

Installation failed, reverting ./composer.json to its original content.

**Comment by gowtham-13** [comment]
+1

**Comment by claudiosanches** [comment]
For what I can see is a problem with how you are using composer and not an issue with this REST API library, so I'm closing it.

**Comment by madebymartin** [comment]
@thgiang it looks like you need to specifiy "version" in your composer.json

http://www.queryadmin.com/1557/composer-no-version-set-parsed-1-0-0-satisfiable/
