### ISSUE TITLE
Can't get more than 10 products from wc-api

### ISSUE THREAD

**Issue by kningzer** [woocommerce/wc-api-php#97]
Hello

I am having the hardest time to retrive all my products from my product library.
Every time i try i only get 10 products.

I have tried a couple of different ways.

My client:
```
	$woocommerce = new Client(
	    constant('API_WC_REST_URL'), 
	     constant('API_WC_REST_CK'), 
	     constant('API_WC_REST_CS'),
	    [
	        'wp_api' => true,
	        'version' => 'wc/v1',
	    ]
	);
```

I have tried:
```
		$parameters  = [
		    'filter' => [
		        'limit' => 30,
		    ],

		];

		$prodlib = $woocommerce->get("products",  $parameters);
```
and:
```
		$prodlib = $woocommerce->get("products");
```

But i always get 10 products. (and yes i tried to adjust my reading setting and such. Not the right way and that does not work for me)

So do anyone have a suggestion for me?
Big thanks in advance

**Comment by pixelpeter** [comment]
With WC 2.6.x or later and WP 4.4 or later you'll have to use the `per_page` parameter.
Please look it up in the documentation

**Comment by kningzer** [comment]
Aaaaaa 

thank you, I'll do that directly!
