### ISSUE TITLE
Set default attributes not possible - wc/v1

### ISSUE THREAD

**Issue by grosssmutttr** [woocommerce/wc-api-php#98]
Tried to add default attributes via:
```
$dataStandVals = [
                "default_attributes" => [
                        [
                        "id" => 1,
                        "option" => 'cool grey/dark grey/dark grey/(white)'
                    ],
                        [
                        "id" => 5,
                        "option" => 'M'
                    ]
                ]
            ];

            try {
                $importedDefAttrProd = $this->api_client->put('products/' . $productID, $dataStandVals);
            } catch (HttpClientException $e) {
                $pContent = print_r($importData, true);
                $error_str .= $e->getMessage() . PHP_EOL;
                $error_str .= $pContent;
                $this->write_error_log($error_str);
                return;
            }

```
Unfortunately this doesn't work and there is no error to debug.

The attributes I try to set as default values are already inserted under the attributes tab.
I double checked the ids and spelling so there shouldn't be an issue with that.

There are five attributes that are used for variations but I only want to set these two as default values.

Attribute id 1 is named "Farbe" and id 5 is named "Größe"

**Comment by claudiosanches** [comment]
Don't sounds like an issue with this REST API lib.
So please use the support forum: https://wordpress.org/support/plugin/woocommerce
